// Bitrefill CDN image resolution for gift card brands
// Shared between gift cards shop page and library page

const BRAND_BITREFILL_SLUGS: Record<string, string> = {
  // === GAMING ===
  'steam':               'steam-usa',
  'steam wallet':        'steam-usa',
  'playstation':         'sony-playstation-usa',
  'playstation store':   'sony-playstation-usa',
  'psn':                 'sony-playstation-usa',
  'ps store':            'sony-playstation-usa',
  'ps plus':             'playstation-plus-usa',
  'playstation plus':    'playstation-plus-usa',
  'xbox':                'xbox-usa',
  'xbox live':           'xbox-usa',
  'xbox game pass':      'xbox-game-pass-ultimate-usa',
  'microsoft':           'microsoft-gift-card-usa',
  'nintendo':            'nintendo-eshop-usa',
  'nintendo eshop':      'nintendo-eshop-usa',
  'nintendo switch':     'nintendo-eshop-usa',
  'roblox':              'roblox-usa',
  'fortnite':            'fortnite-v-bucks-usa',
  'fortnite v-bucks':    'fortnite-v-bucks-usa',
  'epic games':          'epic-games-usa',
  'league of legends':   'league-of-legends-usa',
  'riot games':          'league-of-legends-usa',
  'valorant':            'valorant-usa',
  'minecraft':           'minecraft-usa',
  'pubg':                'pubg-mobile-usa',
  'pubg mobile':         'pubg-mobile-usa',
  'razer gold':          'razer-gold-usa',
  'blizzard':            'blizzard-usa',
  'battle.net':          'blizzard-usa',
  'genshin impact':      'genshin-impact-usa',
  'square enix':         'square-enix-usa',
  'final fantasy':       'square-enix-usa',
  'runescape':           'runescape-usa',
  'apex legends':        'apex-legends-usa',
  'call of duty':        'call-of-duty-usa',
  'garena':              'free-fire-singapore',
  'free fire':           'free-fire-singapore',
  'mobile legends':      'mobile-legends-usa',
  'twitch':              'twitch-usa',
  'gamestop':            'gamestop-usa',
  // === MEGA BRANDS ===
  'amazon':              'amazon-usa',
  'amazon.com':          'amazon-usa',
  'apple':               'apple-gift-card-usa',
  'app store & itunes':  'apple-gift-card-usa',
  'itunes':              'apple-gift-card-usa',
  'google play':         'google-play-australia',
  'visa':                'vanilla-visa-usa',
  'mastercard':          'mastercard-gift-card-usa',
  // === STREAMING ===
  'netflix':             'netflix-usa',
  'spotify':             'spotify-usa',
  'hulu':                'hulu-usa',
  'disney+':             'disney-plus-usa',
  'disney plus':         'disney-plus-usa',
  'crunchyroll':         'crunchyroll-usa',
  // === SHOPPING ===
  'walmart':             'walmart-usa',
  'target':              'target-usa',
  'best buy':            'best-buy-usa',
  'ebay':                'ebay-usa',
  'etsy':                'etsy-usa',
  'nordstrom':           'nordstrom-usa',
  'sephora':             'sephora-usa',
  'nike':                'nike-usa',
  'home depot':          'home-depot-usa',
  // === FOOD ===
  "applebee's":          'applebee_s-guatemala',
  'starbucks':           'starbucks-usa',
  'doordash':            'doordash-usa',
  'grubhub':             'grubhub-usa',
  'chipotle':            'chipotle-usa',
  'mcdonalds':           'mcdonalds-usa',
  "mcdonald's":          'mcdonalds-usa',
  // === TRAVEL ===
  'airbnb':              'airbnb-usa',
  'uber':                'uber-usa',
  'hotels.com':          'hotels_com-usa',
  'fairmont hotel':      'fairmont-hotels-and-resorts-ca',
  // === ENTERTAINMENT ===
  'amc':                 'amc-theatres-usa',
  'amc entertainment':   'amc-theatres-usa',
  'fandango':            'fandango-usa',
  'regal entertainment':           'regal-premiere-ticket-usa',
  'regal entertainment group us':  'regal-premiere-ticket-usa',
  // === SHOPPING (additional) ===
  'banana republic (gap) us':  'banana-republic-usa',
  'banana republic':           'banana-republic-usa',
  'adidas':                    'adidas-usa',
  'gap':                       'gap-usa',
  'old navy':                  'old-navy-usa',
  'h&m':                       'handm-uk',
  'h&m us':                    'handm-uk',
  "macy's":                    'macys-usa',
  "macy's us":                 'macys-usa',
  'abercrombie & fitch us':    'abercrombie-and-fitch-usa',
  'advance auto parts':        'advance-auto-parts-usa',
  'albertsons':                'albertsons-usa',
  'allmodern.com':             'allmodern_com-us',
  'ann taylor':                'ann-taylor-us',
  'aerie':                     'aerie-usa',
  'aeropostale':               'aeropostale-_-apparel-uae',
  'asos':                      'asos-usa',
  'asos us':                   'asos-usa',
  'athleta':                   'athleta-usa',
  'autozone':                  'autozone-usa',
  'baby depot':                'baby-depot-at-burlington-usa',
  'barnes & noble us':         'barnes-and-noble-usa',
  'barnes and nobles':         'barnes-and-noble-usa',
  'baskin robbins':            'baskin-robbins-singapore',
  'bass pro shop':             'bass-pro-shops-usa',
  'lowes':                     'lowe_s-usa',
  '1-800-flowers':             '1-800-flowers-com-usa',
  '1-800-pet supplies':        '1-800-petsupplies-usa',
  '1-800-petsupplies':         '1-800-petsupplies-usa',
  '1-800-baskets':             '1-800-baskets_com-usa',
  // === FOOD (additional) ===
  'subway':                    'subway-usa',
  'dunkin':                    'dunkin-donuts-singapore',
  "domino's":                  'dominos-usa',
  'antie anne':                'auntie-anne_s-thailand',
  'aquarium':                  'aquarium-restaurant-usa',
  'bahama breeze':             'bahama-breeze-island-grille-usa',
  'baja fresh':                'baja-fresh-mexican-grill-usa',
  "baker's square":            'bakers-square-us',
  // === TRAVEL (additional) ===
  'delta airlines':            'delta-air-lines-usa',
  'amtrak':                    'amtrak-usa',
  // === US VARIANT NAMES ===
  'nintendo us':                                    'nintendo-eshop-usa',
  'playstation us':                                 'sony-playstation-usa',
  'xbox us':                                        'xbox-usa',
  'xbox live us':                                   'xbox-usa',
  'xbox game pass 3 month us':                      'xbox-game-pass-ultimate-usa',
  'roblox us':                                      'roblox-usa',
  'steam us':                                       'steam-usa',
  'minecraft us':                                   'minecraft-usa',
  'razer gold (global) us':                         'razer-gold-usa',
  'mobile legends diamonds (global) us':            'mobile-legends-usa',
  'fortnite (standard edition) 1000-v-bucks us':   'fortnite-v-bucks-usa',
  'fortnite (standard edition) 2800-v-bucks us':   'fortnite-v-bucks-usa',
  'fortnite (standard edition) 5000-v-bucks us':   'fortnite-v-bucks-usa',
  'fortnite (standard edition) 13500-v-bucks us':  'fortnite-v-bucks-usa',
  'free fire 100 + 10 diamond us':                 'free-fire-singapore',
  'free fire 210 + 21 diamond us':                 'free-fire-singapore',
  'free fire 530 + 53 diamond us':                 'free-fire-singapore',
  'free fire 1080 + 108 diamond us':               'free-fire-singapore',
  'free fire 2200 + 220 diamond us':               'free-fire-singapore',
  'amazon us':                                     'amazon-usa',
  'app store & itunes us':                         'apple-gift-card-usa',
  'netflix us':                                    'netflix-usa',
  'spotify us':                                    'spotify-usa',
  'hulu plus':                                     'hulu-usa',
  'starbucks us':                                  'starbucks-usa',
  'target us':                                     'target-usa',
  'nordstrom us':                                  'nordstrom-usa',
  'sephora us':                                    'sephora-usa',
  'nike us':                                       'nike-usa',
  'airbnb us':                                     'airbnb-usa',
  'ea 12 month (xbox) us':                         'xbox-usa',
  'pubg mobile uc (global) us':                    'pubg-mobile-usa',
  'pubg new state (global) us':                    'pubg-mobile-usa',
  'babin seafood':                                 'babins-seafood-house-usa',
  'bristol seafood':                               'bristol-seafood-grill-us',
  'build-a-bear':                                  'build-a-bear-uae',
  'devon seafood grill':                           'devon-seafood-grill-us',
  'elearn gift':                                   'elearngift-latvia',
  'famous footwear':                               'famous-footwear-usa',
  'giant eagle':                                   'giant-eagle-us',
  'l.l.bean':                                      'l_l_bean-usa',
  'legal sea foods':                               'legal-sea-foods-usa',
  'omaha steaks':                                  'omaha-steaks-usa',
  'outback steakhouse us':                         'outback-steakhouse-usa',
  "bertucci's":                  'bertucci_s-usa',
  "bill's bar & burguer":        'bills-bar-and-burger-usa',
  'birch lane':                  'birchlane_com-us',
  'blaze pizza':                 'blaze-pizza-us',
  'bob evans':                   'bob-evans-restaurants-us',
  "boscov's":                    'boscovs-usa',
  'br guest hospitality':        'br-guest-hospitality-usa',
  "brenner's stakehouse":        'brenner_s-steakhouse-usa',
  'brick house tavern':          'brick-house-tavern-and-tap-usa',
  'bubba gump':                  'bubba-gump-shrimp-company-usa',
  'bucketlist gift':             'bucketlistgift-se',
  'buffalo wild wings':          'buffalo-wild-wings-usa',
  'burlington':                  'burlington-usa',
  'cadillac bar':                'cadillac-bar-usa',
  'cadillac ranch':              'cadillac-ranch-us',
  'carnival cruises':            'carnival-cruise-lines-usa',
  "carter's":                    'carters-brazil',
  'cb2':                         'cb2-usa',
  'cb2 us':                      'cb2-usa',
  'celebrity cruises':           'celebrity-cruises-usa',
  'chart house':                 'chart-house-usa',
  "cheddar's scratch kitchen":   'cheddars-scratch-kitchen-usa',
  "cheryl's":                    'cheryl_s-cookies-usa',
  'chevron texaco':              'chevron-and-texaco-us',
  'chewy':                       'chewy-usa',
  "chico's":                     'chico_s-usa',
  'chilis':                      'chili_s-grill-and-bar-usa',
  "chuck'e cheese":              'chuck-e_-cheese_s-usa',
  'cinnabon':                    'cinnabon-usa',
  'claim jumper stakehouse & bar': 'claim-jumper-usa',
  'clinkerdagger':               'clinkerdagger-us',
  'conoco':                      'phillips-66-conoco-76-us',
  'cracker barrel':              'cracker-barrel-old-country-store-usa',
  'cost plus':                   'cost-plus-world-market-usa',
  'craft f&b':                   'craft-fandb-us',
  "crate n' kids":               'crate-and-kids-canada',
  'crutchfield':                 'crutchfield-usa',
  "cutter's crabhouse":          'cutters-crabhouse-us',
  'darden restaurants':          'darden-usa',
  'dave & buster':               'dave-and-busters-usa',
  "dick's sporting goods":       'dick_s-sporting-goods-usa',
  'discord nitro':               'discord-nitro-us',
  'dos caminos':                 'dos-caminos-usa',
  'dsw':                         'dsw-everyday-us',
  'exapunks':                    'exapunks-usa',
  'famous dave bbq':             'famous-daves-usa',
  "peet's coffee & tea":                           'peets-coffee-and-tea-usa',
  'royal caribbean':                               'royal-caribbean-usa',
  'season 52':                                     'seasons-52-usa',
  "steak n' shake":                                'steak-_n-shake-usa',
  'the coffee bean & tea leaf':                    'the-coffee-bean-and-tea-leaf-philippines',
  'ulta beauty us':                                'ulta-beauty-usa',
  'paramount plus':                                'paramount-colombia',
  'cbsi paramount plus':                           'paramount-colombia',
  'girls who code':                                'girls-who-code-usa',
  'showtime':                                      'showtime-usa',
  // === W/V/U/T brands ===
  'stubhub':                   'stubhub-usa',
  'stubhub us':                'stubhub-usa',
  'taco bell':                 'taco-bell-malaysia',
  'texas roadhouse':           'texas-roadhouse-usa',
  'the cheesecake factory':    'the-cheesecake-factory-usa',
  'the container store':       'the-container-store-usa',
  'the ocenaire':              'the-oceanaire-seafood-room-usa',
  'the popcorn factory':       'the-popcorn-factory-usa',
  'the vitamin shop':          'the-vitamin-shoppe-us',
  'thredup':                   'thredup-us',
  'tidal':                     'tidal-usa',
  'tjx':                       'tjx-canada',
  'topgolf':                   'topgolf-usa',
  'under armour':              'under-armour-usa',
  'under armour® us':          'under-armour-usa',
  'vic n anthony\'s':          'vic-and-anthony_s-steakhouse-usa',
  'vudu':                      'vudu-_fandango_-us',
  'wayfair':                   'wayfair_ca-canada',
  'wayfair us':                'wayfair_ca-canada',
  'west elm':                  'west-elm-usa',
  'wetgo car wash':            'wetgo-car-wash-locations-us',
  'williams sonoma':           'williams-sonoma-usa',
  'willie g':                  'willie-g_s-seafood-and-steaks-usa',
  'wolferman\'s':              'wolferman_s-usa',
  'yankee candle':             'yankee-candle-usa',
  'yard house':                'yard-house-usa',
  // === R/S brands ===
  'primark':                   'primark-uk',
  'princess cruises':          'princess-cruise-lines-usa',
  'raffles hotels & resort':   'raffles-hotels-and-resorts-usa',
  'rainforest café':           'rainforest-cafe-usa',
  'rainforest cafe':           'rainforest-cafe-usa',
  'red lobster':               'red-lobster-usa',
  'red robin':                 'red-robin-usa',
  'rei':                       'rei-usa',
  'river crab/blue water inn': 'river-crab-_-bluewater-inn-usa',
  "ruth's chris stakehouse":   'ruths-chris-steakhouse-usa',
  "ruth's chris steakhouse":   'ruths-chris-steakhouse-usa',
  'safeway':                   'safeway-ca',
  'saks fifth avenue':         'saks-fifth-avenue-usa',
  'saltgrass stakehouse':      'saltgrass-steakhouse-usa',
  "sam's club":                'cashi-sams-club-mexico',
  'sheetz':                    'sheetz-usa',
  'shutterfly':                'shutterfly-usa',
  'sierra':                    'sierra-trading-post-usa',
  'simply chocolate':          'simply-chocolate-usa',
  'sirius xm':                 'siriusxm-usa',
  'sonic app':                 'sonic-us',
  'southwest airlines':        'southwest-airlines-usa',
  'sportsmans warehouse':      'sportsman_s-warehouse-usa',
  'staples':                   'staples-usa',
  'stitch fix':                'stitch-fix-usa',
  'stock yards':               'stock-yards-usa',
  'strip house':               'strip-house-usa',
  // === F/G brands ===
  'fanatics':                  'fanatics-usa',
  'finish line':               'finish-line-us',
  'fish tales':                'fish-tales-usa',
  "fisherman's wharf":         'fisherman_s-wharf-seafood-grill-usa',
  'five guys':                 'five-guys-de',
  "flemming's stakehouse":     'flemings-prime-steakhouse-and-wine-bar-usa',
  'flying dutchman':           'flying-dutchman-usa',
  'fragrancenet.com':          'fragrancenet_com-usa',
  "fricker's sports bar":      'fricker_s-us',
  'fruit bouquets':            'fruit-bouquets-usa',
  'gander outdoors':           'gander-outdoors-usa',
  'gandy dancer':              'gandy-dancer-usa',
  'global experiencies':       'global-experience-card-hu',
  'global hotel':              'global-hotel-card-japan',
  'go play golf':              'go-play-golf-usa',
  'go rio cruises':            'go-rio-san-antonio-river-cruises-us',
  'golden nugget casino':      'golden-nugget-usa',
  'goodcents':                 'goodcents-usa',
  'grotto':                    'grotto-usa',
  'groupon':                   'groupon-canada',
  'groupon us':                'groupon-canada',
  'guess':                     'guess-ae',
  'guild wars':                'guild-wars-2-gem-card-us',
  'guitar center':             'guitar-center-usa',
  // === H/I brands ===
  'hard rock cafe':            'hard-rock-cafe-usa',
  "harry n' david":            'harry-and-david-usa',
  'home chef':                 'home-chef-usa',
  "horatio's":                 'horatio_s-us',
  'ifly':                      'ifly-usa',
  'imvu':                      'imvu-usa',
  // === M/N/O/P brands ===
  'maurices':                        'maurices-us',
  'mc. cormick & schmick':           'mccormick-and-schmick_s-usa',
  "mitchell's fish market":          'mitchell_s-fish-market-usa',
  "mitchell's stakehouse":           'mitchell_s-steakhouse-usa',
  'mix it up':                       'mix-it-up-usa',
  "moe's southwest grill":           'moe_s-southwest-grill-us',
  "morton's the stakehouse":         'morton_s-the-steakhouse-usa',
  'nasty gal':                       'nastygal-us',
  'nautica':                         'nautica-usa',
  'nba store':                       'nba-store-usa',
  'netdragon universal (global) us': 'netdragon-universal-usa',
  'nfl shop':                        'nflshop_com-usa',
  'nhl shop':                        'nhl-shop-usa',
  'ninety nine':                     'ninety-nine-restaurant-and-pub-us',
  "o'charley's":                     'o_charley_s-us',
  'p.c. richard & son':              'p_c_-richard-and-son-usa',
  'panda express':                   'panda-express-us',
  'panera':                          'panera-bread-usa',
  'papa johns':                      'papa-john_s-usa',
  'perigold':                        'perigold-us',
  'pinkberry':                       'pinkberry-usa',
  'p. f. changs':                    'pf-chang_s-argentina-argentina',
  'pottery barn':                    'pottery-barn-usa',
  // === I/J/K/L/M brands ===
  'instacart':                  'instacart-usa',
  "j. gilbert's":               'j_gilbert_s-us',
  "jake's grill":               'jake_s-grill-us',
  'jamba juice':                'jamba-juice-php',
  'jawaker us':                 'jawaker-lithuania',
  'jc penney':                  'jc-penney-usa',
  'jcpenney':                   'jc-penney-usa',
  'jersey mike':                'jersey-mike_s-usa',
  'jiffy lube':                 'jiffy-lube-usa',
  'jtv':                        'jtv_com-us',
  'kemah boardwalk':            'keemah-boardwalk-usa',
  'kigso games':                'kigso-usa',
  'king ranch texas kitchen':   'king-ranch-texas-kitchen-us',
  "kohl's":                     'kohl_s-usa',
  'krispy kreme':               'krispy-kreme-usa',
  'kroger':                     'kroger-usa',
  'la griglia':                 'la-griglia-usa',
  'logan road hosue':           'logan_s-roadhouse-usa',
  'lululemon':                  'lululemon-usa',
  'lululemon us':               'lululemon-usa',
  "maggiano's":                 'maggianos-little-italy-usa',
  'maggie bluffs':              'maggie-bluffs-us',
  'mai tar bar':                'mai-tai-bar-usa',
  'main event':                 'main-event-us',
  'mandarin oriental':          'mandarin-oriental-hotel-group-us',
  'mark and graham':            'mark-and-graham-usa',
  'marshalls':                  'marshalls-usa',
}

export function getBitrefillImageUrl(brand: string): string | null {
  const slug = BRAND_BITREFILL_SLUGS[brand.toLowerCase().trim()]
  return slug ? `https://cdn.bitrefill.com/primg/w360h216/${slug}.webp` : null
}

// ── Brand gradient colors ──────────────────────────────────────────────────
// Used by GiftCardVisual as a fallback when Bitrefill has no artwork

export const BRAND_COLORS: Record<string, [string, string]> = {
  // Gaming
  'xbox':                   ['#107C10','#0a5a0a'],
  'xbox live':              ['#107C10','#0a5a0a'],
  'xbox game pass':         ['#107C10','#0a5a0a'],
  'playstation':            ['#003087','#0059c2'],
  'playstation store':      ['#003087','#0059c2'],
  'psn':                    ['#003087','#0059c2'],
  'ps plus':                ['#003087','#0059c2'],
  'steam':                  ['#1b2838','#2a475e'],
  'nintendo':               ['#E4000F','#9e0000'],
  'nintendo eshop':         ['#E4000F','#9e0000'],
  'roblox':                 ['#E8002B','#8b0000'],
  'fortnite':               ['#1d1046','#9d4dca'],
  'fortnite v-bucks':       ['#1d1046','#9d4dca'],
  'minecraft':              ['#5c7a1f','#3a5012'],
  'league of legends':      ['#C89B3C','#785a28'],
  'valorant':               ['#FF4655','#8b0000'],
  'twitch':                 ['#6441a5','#9146FF'],
  'blizzard':               ['#148EFF','#0e6bbf'],
  'epic games':             ['#2d2d2d','#000000'],
  'razer gold':             ['#44D62C','#2a8a1a'],
  'apex legends':           ['#CD3333','#6b0000'],
  'call of duty':           ['#1a1a1a','#3d3d3d'],
  'pubg':                   ['#F5A623','#c07c0e'],
  'pubg mobile':            ['#F5A623','#c07c0e'],
  'genshin impact':         ['#4a90d9','#1a3a6b'],
  'mobile legends':         ['#1a1a2e','#c0392b'],
  'free fire':              ['#ff6b00','#c04e00'],
  'garena':                 ['#ff6b00','#c04e00'],
  'square enix':            ['#1a1a1a','#3d3d3d'],
  'runescape':              ['#8B4513','#5c2c0a'],
  'gamestop':               ['#E31A22','#9e0000'],
  'discord':                ['#5865F2','#404EED'],
  // Mega brands
  'amazon':                 ['#FF9900','#c97200'],
  'amazon us':              ['#FF9900','#c97200'],
  'apple':                  ['#555555','#1d1d1d'],
  'app store & itunes':     ['#555555','#1d1d1d'],
  'itunes':                 ['#555555','#1d1d1d'],
  'google play':            ['#01875f','#34a853'],
  'visa':                   ['#1A1F71','#0d1245'],
  'mastercard':             ['#EB001B','#c00014'],
  // Streaming
  'netflix':                ['#E50914','#8B0000'],
  'spotify':                ['#1DB954','#158a3e'],
  'hulu':                   ['#1CE783','#0fa35c'],
  'disney+':                ['#113CCF','#051a6e'],
  'disney plus':            ['#113CCF','#051a6e'],
  'crunchyroll':            ['#F47521','#c45810'],
  'paramount plus':         ['#0064FF','#0041a8'],
  'cbsi paramount plus':    ['#0064FF','#0041a8'],
  'tidal':                  ['#111111','#333333'],
  'showtime':               ['#CC0000','#8b0000'],
  'sling tv':               ['#1d6fe8','#0d4db5'],
  // Shopping
  'walmart':                ['#0071CE','#004f94'],
  'target':                 ['#CC0000','#8b0000'],
  'best buy':               ['#0046BE','#003494'],
  'ebay':                   ['#E53238','#0064D2'],
  'nike':                   ['#111111','#333333'],
  'adidas':                 ['#000000','#1a1a1a'],
  'nordstrom':              ['#1a1a1a','#3d3d3d'],
  'sephora':                ['#111111','#333333'],
  'ulta':                   ['#000000','#1a1a1a'],
  'lululemon':              ['#CC0000','#8b0000'],
  'under armour':           ['#1a1a1a','#CC0000'],
  'home depot':             ['#F96302','#c24c00'],
  'the home depot':         ['#F96302','#c24c00'],
  'gap':                    ['#0C4DA2','#083580'],
  'old navy':               ['#0C4DA2','#083580'],
  'banana republic':        ['#2d2d2d','#1a1a1a'],
  'athleta':                ['#1a1a1a','#2d2d2d'],
  'aerie':                  ['#c0687a','#8b3a4f'],
  'aeropostale':            ['#1a2a5e','#0d1a3d'],
  "macy's":                 ['#E21A22','#9e0000'],
  "kohl's":                 ['#6b1a1a','#3d0a0a'],
  'jc penney':              ['#1a1a1a','#3d3d3d'],
  'tjx':                    ['#CC0000','#8b0000'],
  'marshalls':              ['#CC0000','#8b0000'],
  'home goods':             ['#CC0000','#8b0000'],
  'home sense':             ['#CC0000','#8b0000'],
  'sierra':                 ['#2d6b2d','#1a3a1a'],
  'wayfair':                ['#7B2D8B','#4a1a57'],
  'birch lane':             ['#5C3D2E','#3a2519'],
  'joss and main':          ['#2d2d2d','#1a1a1a'],
  'perigold':               ['#8B7355','#5c4a35'],
  'pottery barn':           ['#5C3D2E','#3a2519'],
  'west elm':               ['#1a1a1a','#2d2d2d'],
  'williams sonoma':        ['#8B0000','#5c0000'],
  "crate n' kids":          ['#1a3a6b','#0d1f45'],
  'cb2':                    ['#1a1a1a','#000000'],
  'etsy':                   ['#F45800','#b83f00'],
  "sam's club":             ['#0071CE','#004f94'],
  'home chef':              ['#FF6B35','#c04a1f'],
  // Food & dining
  'starbucks':              ['#00704A','#004d33'],
  'doordash':               ['#FF3008','#cc2500'],
  'uber':                   ['#000000','#1a1a1a'],
  'chipotle':               ['#A81612','#7a0f0d'],
  'mcdonalds':              ['#FFC72C','#DA291C'],
  "mcdonald's":             ['#FFC72C','#DA291C'],
  'subway':                 ['#009B48','#FFC600'],
  'taco bell':              ['#702082','#4b1559'],
  'dunkin':                 ['#FF6E0F','#DD1D21'],
  'papa johns':             ['#CC0000','#006747'],
  "domino's":               ['#006491','#CC0000'],
  'panera':                 ['#6B3A2A','#4a2519'],
  'krispy kreme':           ['#CC0000','#267c37'],
  'five guys':              ['#CC0000','#e8c800'],
  'buffalo wild wings':     ['#F4C31D','#CC0000'],
  'chilis':                 ['#CC0000','#8b0000'],
  'red robin':              ['#CC0000','#FFD700'],
  'cracker barrel':         ['#8B0000','#4a0000'],
  'texas roadhouse':        ['#CC0000','#8b0000'],
  'outback steakhouse':     ['#CC0000','#8b0000'],
  'red lobster':            ['#CC0000','#8b0000'],
  'the cheesecake factory': ['#8B0000','#5C3D2E'],
  'panda express':          ['#CC0000','#1a1a1a'],
  'sonic app':              ['#1B428A','#E31C1C'],
  'sonic':                  ['#1B428A','#E31C1C'],
  'jersey mike':            ['#CC0000','#8b0000'],
  'jamba juice':            ['#F5A623','#c07c0e'],
  'instacart':              ['#43B02A','#2d7a1c'],
  'starbucks us':           ['#00704A','#004d33'],
  // Travel
  'airbnb':                 ['#FF5A5F','#e04045'],
  'delta airlines':         ['#003366','#cc0000'],
  'southwest airlines':     ['#304CB2','#F9B612'],
  'royal caribbean':        ['#003087','#0077C8'],
  'carnival cruises':       ['#CC0000','#003087'],
  'hotels.com':             ['#CC0000','#8b0000'],
  'amtrak':                 ['#1a3a6b','#CC0000'],
  // Entertainment
  'amc':                    ['#1a1a1a','#cc0000'],
  'fandango':               ['#5C2483','#3a1657'],
  'stubhub':                ['#003168','#0057B8'],
  'regal entertainment':    ['#1a1a1a','#cc0000'],
  'topgolf':                ['#1a3a1a','#2d6b2d'],
  'dave & buster':          ['#CC0000','#1a1a1a'],
  'sirius xm':              ['#003087','#0057b3'],
  // Outdoor / Auto
  'jiffy lube':             ['#F5A623','#E8001B'],
  // Sports
  'nba store':              ['#1d428a','#CC0000'],
  'nfl shop':               ['#013369','#D50A0A'],
  'nhl shop':               ['#000000','#1a1a1a'],
  // Misc
  'groupon':                ['#53A318','#3a7210'],
  "lowe's":                 ['#004990','#003060'],
  'lowes':                  ['#004990','#003060'],
  'paypal':                 ['#003087','#009cde'],
  'airalo':                 ['#6C63FF','#4a42cc'],
}

export const CATEGORY_COLORS: Record<string, [string, string]> = {
  gaming:        ['#2d1b69','#4B0082'],
  streaming:     ['#8B0000','#cc0000'],
  shopping:      ['#003d7a','#0057b3'],
  food:          ['#6B2D0A','#a84412'],
  travel:        ['#003366','#0057b3'],
  entertainment: ['#1a0033','#4B0082'],
  retail:        ['#1a2e1a','#2d4d2d'],
  payment:       ['#1a1a2e','#2d2d5a'],
  other:         ['#1a1a2e','#2d2d3d'],
}

export function hashBrandColor(brand: string): [string, string] {
  let hash = 0
  for (let i = 0; i < brand.length; i++) {
    hash = brand.charCodeAt(i) + ((hash << 5) - hash)
  }
  const h = Math.abs(hash) % 360
  return [`hsl(${h}, 55%, 25%)`, `hsl(${h}, 65%, 15%)`]
}

export function getBrandColors(brand: string, category: string): [string, string] {
  const key = brand.toLowerCase().trim()
  if (BRAND_COLORS[key]) return BRAND_COLORS[key]
  for (const [k, colors] of Object.entries(BRAND_COLORS)) {
    if (key.includes(k) || k.includes(key)) return colors
  }
  return CATEGORY_COLORS[category?.toLowerCase()] || hashBrandColor(brand)
}
