// Bitrefill CDN image resolution for gift card brands
// Shared between gift cards shop page and library page

const BRAND_BITREFILL_SLUGS: Record<string, string> = {
  // === GAMING ===
  'steam':               'steam-usa',
  'steam wallet':        'steam-usa',
  'playstation':         'sony-playstation-usa',
  'playstation store':   'sony-playstation-usa',
  'psn':                 'sony-playstation-usa',
  'ps store':            'sony-playstation-usa',
  'ps plus':             'playstation-plus-usa',
  'playstation plus':    'playstation-plus-usa',
  'xbox':                'xbox-usa',
  'xbox live':           'xbox-usa',
  'xbox game pass':      'xbox-game-pass-ultimate-usa',
  'microsoft':           'microsoft-gift-card-usa',
  'nintendo':            'nintendo-eshop-usa',
  'nintendo eshop':      'nintendo-eshop-usa',
  'nintendo switch':     'nintendo-eshop-usa',
  'roblox':              'roblox-usa',
  'fortnite':            'fortnite-v-bucks-usa',
  'fortnite v-bucks':    'fortnite-v-bucks-usa',
  'epic games':          'epic-games-usa',
  'league of legends':   'league-of-legends-usa',
  'riot games':          'league-of-legends-usa',
  'valorant':            'valorant-usa',
  'minecraft':           'minecraft-usa',
  'pubg':                'pubg-mobile-usa',
  'pubg mobile':         'pubg-mobile-usa',
  'razer gold':          'razer-gold-usa',
  'blizzard':            'blizzard-usa',
  'battle.net':          'blizzard-usa',
  'genshin impact':      'genshin-impact-usa',
  'square enix':         'square-enix-usa',
  'final fantasy':       'square-enix-usa',
  'runescape':           'runescape-usa',
  'apex legends':        'apex-legends-usa',
  'call of duty':        'call-of-duty-usa',
  'garena':              'free-fire-singapore',
  'free fire':           'free-fire-singapore',
  'mobile legends':      'mobile-legends-usa',
  'twitch':              'twitch-usa',
  'gamestop':            'gamestop-usa',
  // === MEGA BRANDS ===
  'amazon':              'amazon-usa',
  'amazon.com':          'amazon-usa',
  'apple':               'apple-gift-card-usa',
  'app store & itunes':  'apple-gift-card-usa',
  'itunes':              'apple-gift-card-usa',
  'google play':         'google-play-australia',
  'visa':                'vanilla-visa-usa',
  'mastercard':          'mastercard-gift-card-usa',
  // === STREAMING ===
  'netflix':             'netflix-usa',
  'spotify':             'spotify-usa',
  'hulu':                'hulu-usa',
  'disney+':             'disney-plus-usa',
  'disney plus':         'disney-plus-usa',
  'crunchyroll':         'crunchyroll-usa',
  // === SHOPPING ===
  'walmart':             'walmart-usa',
  'target':              'target-usa',
  'best buy':            'best-buy-usa',
  'ebay':                'ebay-usa',
  'etsy':                'etsy-usa',
  'nordstrom':           'nordstrom-usa',
  'sephora':             'sephora-usa',
  'nike':                'nike-usa',
  'home depot':          'home-depot-usa',
  // === FOOD ===
  "applebee's":          'applebee_s-guatemala',
  'starbucks':           'starbucks-usa',
  'doordash':            'doordash-usa',
  'grubhub':             'grubhub-usa',
  'chipotle':            'chipotle-usa',
  'mcdonalds':           'mcdonalds-usa',
  "mcdonald's":          'mcdonalds-usa',
  // === TRAVEL ===
  'airbnb':              'airbnb-usa',
  'uber':                'uber-usa',
  'hotels.com':          'hotels_com-usa',
  'fairmont hotel':      'fairmont-hotels-and-resorts-ca',
  // === ENTERTAINMENT ===
  'amc':                 'amc-theatres-usa',
  'amc entertainment':   'amc-theatres-usa',
  'fandango':            'fandango-usa',
  'regal entertainment':           'regal-premiere-ticket-usa',
  'regal entertainment group us':  'regal-premiere-ticket-usa',
  // === SHOPPING (additional) ===
  'banana republic (gap) us':  'banana-republic-usa',
  'banana republic':           'banana-republic-usa',
  'adidas':                    'adidas-usa',
  'gap':                       'gap-usa',
  'old navy':                  'old-navy-usa',
  'h&m':                       'handm-uk',
  'h&m us':                    'handm-uk',
  "macy's":                    'macys-usa',
  "macy's us":                 'macys-usa',
  'abercrombie & fitch us':    'abercrombie-and-fitch-usa',
  'advance auto parts':        'advance-auto-parts-usa',
  'albertsons':                'albertsons-usa',
  'allmodern.com':             'allmodern_com-us',
  'ann taylor':                'ann-taylor-us',
  'aerie':                     'aerie-usa',
  'aeropostale':               'aeropostale-_-apparel-uae',
  'asos':                      'asos-usa',
  'asos us':                   'asos-usa',
  'athleta':                   'athleta-usa',
  'autozone':                  'autozone-usa',
  'baby depot':                'baby-depot-at-burlington-usa',
  'barnes & noble us':         'barnes-and-noble-usa',
  'barnes and nobles':         'barnes-and-noble-usa',
  'baskin robbins':            'baskin-robbins-singapore',
  'bass pro shop':             'bass-pro-shops-usa',
  'lowes':                     'lowe_s-usa',
  '1-800-flowers':             '1-800-flowers-com-usa',
  '1-800-pet supplies':        '1-800-petsupplies-usa',
  '1-800-petsupplies':         '1-800-petsupplies-usa',
  '1-800-baskets':             '1-800-baskets_com-usa',
  // === FOOD (additional) ===
  'subway':                    'subway-usa',
  'dunkin':                    'dunkin-donuts-singapore',
  "domino's":                  'dominos-usa',
  'antie anne':                'auntie-anne_s-thailand',
  'aquarium':                  'aquarium-restaurant-usa',
  'bahama breeze':             'bahama-breeze-island-grille-usa',
  'baja fresh':                'baja-fresh-mexican-grill-usa',
  "baker's square":            'bakers-square-us',
  // === TRAVEL (additional) ===
  'delta airlines':            'delta-air-lines-usa',
  'amtrak':                    'amtrak-usa',
  // === US VARIANT NAMES ===
  'nintendo us':                                    'nintendo-eshop-usa',
  'playstation us':                                 'sony-playstation-usa',
  'xbox us':                                        'xbox-usa',
  'xbox live us':                                   'xbox-usa',
  'xbox game pass 3 month us':                      'xbox-game-pass-ultimate-usa',
  'roblox us':                                      'roblox-usa',
  'steam us':                                       'steam-usa',
  'minecraft us':                                   'minecraft-usa',
  'razer gold (global) us':                         'razer-gold-usa',
  'mobile legends diamonds (global) us':            'mobile-legends-usa',
  'fortnite (standard edition) 1000-v-bucks us':   'fortnite-v-bucks-usa',
  'fortnite (standard edition) 2800-v-bucks us':   'fortnite-v-bucks-usa',
  'fortnite (standard edition) 5000-v-bucks us':   'fortnite-v-bucks-usa',
  'fortnite (standard edition) 13500-v-bucks us':  'fortnite-v-bucks-usa',
  'free fire 100 + 10 diamond us':                 'free-fire-singapore',
  'free fire 210 + 21 diamond us':                 'free-fire-singapore',
  'free fire 530 + 53 diamond us':                 'free-fire-singapore',
  'free fire 1080 + 108 diamond us':               'free-fire-singapore',
  'free fire 2200 + 220 diamond us':               'free-fire-singapore',
  'amazon us':                                     'amazon-usa',
  'app store & itunes us':                         'apple-gift-card-usa',
  'netflix us':                                    'netflix-usa',
  'spotify us':                                    'spotify-usa',
  'hulu plus':                                     'hulu-usa',
  'starbucks us':                                  'starbucks-usa',
  'target us':                                     'target-usa',
  'nordstrom us':                                  'nordstrom-usa',
  'sephora us':                                    'sephora-usa',
  'nike us':                                       'nike-usa',
  'airbnb us':                                     'airbnb-usa',
  'ea 12 month (xbox) us':                         'xbox-usa',
  'pubg mobile uc (global) us':                    'pubg-mobile-usa',
  'pubg new state (global) us':                    'pubg-mobile-usa',
  'babin seafood':                                 'babins-seafood-house-usa',
  'bristol seafood':                               'bristol-seafood-grill-us',
  'build-a-bear':                                  'build-a-bear-uae',
  'devon seafood grill':                           'devon-seafood-grill-us',
  'elearn gift':                                   'elearngift-latvia',
  'famous footwear':                               'famous-footwear-usa',
  'giant eagle':                                   'giant-eagle-us',
  'l.l.bean':                                      'l_l_bean-usa',
  'legal sea foods':                               'legal-sea-foods-usa',
  'omaha steaks':                                  'omaha-steaks-usa',
  'outback steakhouse us':                         'outback-steakhouse-usa',
  "bertucci's":                  'bertucci_s-usa',
  "bill's bar & burguer":        'bills-bar-and-burger-usa',
  'birch lane':                  'birchlane_com-us',
  'blaze pizza':                 'blaze-pizza-us',
  'bob evans':                   'bob-evans-restaurants-us',
  "boscov's":                    'boscovs-usa',
  'br guest hospitality':        'br-guest-hospitality-usa',
  "brenner's stakehouse":        'brenner_s-steakhouse-usa',
  'brick house tavern':          'brick-house-tavern-and-tap-usa',
  'bubba gump':                  'bubba-gump-shrimp-company-usa',
  'bucketlist gift':             'bucketlistgift-se',
  'buffalo wild wings':          'buffalo-wild-wings-usa',
  'burlington':                  'burlington-usa',
  'cadillac bar':                'cadillac-bar-usa',
  'cadillac ranch':              'cadillac-ranch-us',
  'carnival cruises':            'carnival-cruise-lines-usa',
  "carter's":                    'carters-brazil',
  'cb2':                         'cb2-usa',
  'cb2 us':                      'cb2-usa',
  'celebrity cruises':           'celebrity-cruises-usa',
  'chart house':                 'chart-house-usa',
  "cheddar's scratch kitchen":   'cheddars-scratch-kitchen-usa',
  "cheryl's":                    'cheryl_s-cookies-usa',
  'chevron texaco':              'chevron-and-texaco-us',
  'chewy':                       'chewy-usa',
  "chico's":                     'chico_s-usa',
  'chilis':                      'chili_s-grill-and-bar-usa',
  "chuck'e cheese":              'chuck-e_-cheese_s-usa',
  'cinnabon':                    'cinnabon-usa',
  'claim jumper stakehouse & bar': 'claim-jumper-usa',
  'clinkerdagger':               'clinkerdagger-us',
  'conoco':                      'phillips-66-conoco-76-us',
  'cracker barrel':              'cracker-barrel-old-country-store-usa',
  'cost plus':                   'cost-plus-world-market-usa',
  'craft f&b':                   'craft-fandb-us',
  "crate n' kids":               'crate-and-kids-canada',
  'crutchfield':                 'crutchfield-usa',
  "cutter's crabhouse":          'cutters-crabhouse-us',
  'darden restaurants':          'darden-usa',
  'dave & buster':               'dave-and-busters-usa',
  "dick's sporting goods":       'dick_s-sporting-goods-usa',
  'discord nitro':               'discord-nitro-us',
  'dos caminos':                 'dos-caminos-usa',
  'dsw':                         'dsw-everyday-us',
  'exapunks':                    'exapunks-usa',
  'famous dave bbq':             'famous-daves-usa',
  "peet's coffee & tea":                           'peets-coffee-and-tea-usa',
  'royal caribbean':                               'royal-caribbean-usa',
  'season 52':                                     'seasons-52-usa',
  "steak n' shake":                                'steak-_n-shake-usa',
  'the coffee bean & tea leaf':                    'the-coffee-bean-and-tea-leaf-philippines',
  'ulta beauty us':                                'ulta-beauty-usa',
  'paramount plus':                                'paramount-colombia',
  'cbsi paramount plus':                           'paramount-colombia',
  'girls who code':                                'girls-who-code-usa',
  'showtime':                                      'showtime-usa',
  // === W/V/U/T brands ===
  'stubhub':                   'stubhub-usa',
  'stubhub us':                'stubhub-usa',
  'taco bell':                 'taco-bell-malaysia',
  'texas roadhouse':           'texas-roadhouse-usa',
  'the cheesecake factory':    'the-cheesecake-factory-usa',
  'the container store':       'the-container-store-usa',
  'the ocenaire':              'the-oceanaire-seafood-room-usa',
  'the popcorn factory':       'the-popcorn-factory-usa',
  'the vitamin shop':          'the-vitamin-shoppe-us',
  'thredup':                   'thredup-us',
  'tidal':                     'tidal-usa',
  'tjx':                       'tjx-canada',
  'topgolf':                   'topgolf-usa',
  'under armour':              'under-armour-usa',
  'under armour® us':          'under-armour-usa',
  'vic n anthony\'s':          'vic-and-anthony_s-steakhouse-usa',
  'vudu':                      'vudu-_fandango_-us',
  'wayfair':                   'wayfair_ca-canada',
  'wayfair us':                'wayfair_ca-canada',
  'west elm':                  'west-elm-usa',
  'wetgo car wash':            'wetgo-car-wash-locations-us',
  'williams sonoma':           'williams-sonoma-usa',
  'willie g':                  'willie-g_s-seafood-and-steaks-usa',
  'wolferman\'s':              'wolferman_s-usa',
  'yankee candle':             'yankee-candle-usa',
  'yard house':                'yard-house-usa',
  // === R/S brands ===
  'primark':                   'primark-uk',
  'princess cruises':          'princess-cruise-lines-usa',
  'raffles hotels & resort':   'raffles-hotels-and-resorts-usa',
  'rainforest café':           'rainforest-cafe-usa',
  'rainforest cafe':           'rainforest-cafe-usa',
  'red lobster':               'red-lobster-usa',
  'red robin':                 'red-robin-usa',
  'rei':                       'rei-usa',
  'river crab/blue water inn': 'river-crab-_-bluewater-inn-usa',
  "ruth's chris stakehouse":   'ruths-chris-steakhouse-usa',
  "ruth's chris steakhouse":   'ruths-chris-steakhouse-usa',
  'safeway':                   'safeway-ca',
  'saks fifth avenue':         'saks-fifth-avenue-usa',
  'saltgrass stakehouse':      'saltgrass-steakhouse-usa',
  "sam's club":                'cashi-sams-club-mexico',
  'sheetz':                    'sheetz-usa',
  'shutterfly':                'shutterfly-usa',
  'sierra':                    'sierra-trading-post-usa',
  'simply chocolate':          'simply-chocolate-usa',
  'sirius xm':                 'siriusxm-usa',
  'sonic app':                 'sonic-us',
  'southwest airlines':        'southwest-airlines-usa',
  'sportsmans warehouse':      'sportsman_s-warehouse-usa',
  'staples':                   'staples-usa',
  'stitch fix':                'stitch-fix-usa',
  'stock yards':               'stock-yards-usa',
  'strip house':               'strip-house-usa',
  // === F/G brands ===
  'fanatics':                  'fanatics-usa',
  'finish line':               'finish-line-us',
  'fish tales':                'fish-tales-usa',
  "fisherman's wharf":         'fisherman_s-wharf-seafood-grill-usa',
  'five guys':                 'five-guys-de',
  "flemming's stakehouse":     'flemings-prime-steakhouse-and-wine-bar-usa',
  'flying dutchman':           'flying-dutchman-usa',
  'fragrancenet.com':          'fragrancenet_com-usa',
  "fricker's sports bar":      'fricker_s-us',
  'fruit bouquets':            'fruit-bouquets-usa',
  'gander outdoors':           'gander-outdoors-usa',
  'gandy dancer':              'gandy-dancer-usa',
  'global experiencies':       'global-experience-card-hu',
  'global hotel':              'global-hotel-card-japan',
  'go play golf':              'go-play-golf-usa',
  'go rio cruises':            'go-rio-san-antonio-river-cruises-us',
  'golden nugget casino':      'golden-nugget-usa',
  'goodcents':                 'goodcents-usa',
  'grotto':                    'grotto-usa',
  'groupon':                   'groupon-canada',
  'groupon us':                'groupon-canada',
  'guess':                     'guess-ae',
  'guild wars':                'guild-wars-2-gem-card-us',
  'guitar center':             'guitar-center-usa',
  // === H/I brands ===
  'hard rock cafe':            'hard-rock-cafe-usa',
  "harry n' david":            'harry-and-david-usa',
  'home chef':                 'home-chef-usa',
  "horatio's":                 'horatio_s-us',
  'ifly':                      'ifly-usa',
  'imvu':                      'imvu-usa',
  // === M/N/O/P brands ===
  'maurices':                        'maurices-us',
  'mc. cormick & schmick':           'mccormick-and-schmick_s-usa',
  "mitchell's fish market":          'mitchell_s-fish-market-usa',
  "mitchell's stakehouse":           'mitchell_s-steakhouse-usa',
  'mix it up':                       'mix-it-up-usa',
  "moe's southwest grill":           'moe_s-southwest-grill-us',
  "morton's the stakehouse":         'morton_s-the-steakhouse-usa',
  'nasty gal':                       'nastygal-us',
  'nautica':                         'nautica-usa',
  'nba store':                       'nba-store-usa',
  'netdragon universal (global) us': 'netdragon-universal-usa',
  'nfl shop':                        'nflshop_com-usa',
  'nhl shop':                        'nhl-shop-usa',
  'ninety nine':                     'ninety-nine-restaurant-and-pub-us',
  "o'charley's":                     'o_charley_s-us',
  'p.c. richard & son':              'p_c_-richard-and-son-usa',
  'panda express':                   'panda-express-us',
  'panera':                          'panera-bread-usa',
  'papa johns':                      'papa-john_s-usa',
  'perigold':                        'perigold-us',
  'pinkberry':                       'pinkberry-usa',
  'p. f. changs':                    'pf-chang_s-argentina-argentina',
  'pottery barn':                    'pottery-barn-usa',
  // === I/J/K/L/M brands ===
  'instacart':                  'instacart-usa',
  "j. gilbert's":               'j_gilbert_s-us',
  "jake's grill":               'jake_s-grill-us',
  'jamba juice':                'jamba-juice-php',
  'jawaker us':                 'jawaker-lithuania',
  'jc penney':                  'jc-penney-usa',
  'jcpenney':                   'jc-penney-usa',
  'jersey mike':                'jersey-mike_s-usa',
  'jiffy lube':                 'jiffy-lube-usa',
  'jtv':                        'jtv_com-us',
  'kemah boardwalk':            'keemah-boardwalk-usa',
  'kigso games':                'kigso-usa',
  'king ranch texas kitchen':   'king-ranch-texas-kitchen-us',
  "kohl's":                     'kohl_s-usa',
  'krispy kreme':               'krispy-kreme-usa',
  'kroger':                     'kroger-usa',
  'la griglia':                 'la-griglia-usa',
  'logan road hosue':           'logan_s-roadhouse-usa',
  'lululemon':                  'lululemon-usa',
  'lululemon us':               'lululemon-usa',
  "maggiano's":                 'maggianos-little-italy-usa',
  'maggie bluffs':              'maggie-bluffs-us',
  'mai tar bar':                'mai-tai-bar-usa',
  'main event':                 'main-event-us',
  'mandarin oriental':          'mandarin-oriental-hotel-group-us',
  'mark and graham':            'mark-and-graham-usa',
  'marshalls':                  'marshalls-usa',
}

export function getBitrefillImageUrl(brand: string): string | null {
  const slug = BRAND_BITREFILL_SLUGS[brand.toLowerCase().trim()]
  return slug ? `https://cdn.bitrefill.com/primg/w360h216/${slug}.webp` : null
}
