'use client'

import { useState, useEffect } from 'react'

interface ServiceLogoProps {
  name: string
  size?: number
  className?: string
}

// Map service names to their domains for logo fetching
const SERVICE_DOMAINS: Record<string, string> = {
  // Social & Messaging
  whatsapp: 'whatsapp.com',
  telegram: 'telegram.org',
  facebook: 'facebook.com',
  instagram: 'instagram.com',
  twitter: 'twitter.com',
  x: 'x.com',
  tiktok: 'tiktok.com',
  discord: 'discord.com',
  snapchat: 'snapchat.com',
  linkedin: 'linkedin.com',
  reddit: 'reddit.com',
  pinterest: 'pinterest.com',
  youtube: 'youtube.com',
  twitch: 'twitch.tv',
  clubhouse: 'clubhouse.com',
  threads: 'threads.net',
  mastodon: 'mastodon.social',
  bluesky: 'bsky.app',
  vk: 'vk.com',
  odnoklassniki: 'ok.ru',
  weibo: 'weibo.com',
  qq: 'qq.com',
  wechat: 'wechat.com',
  kakaotalk: 'kakaocorp.com',
  line: 'line.me',
  viber: 'viber.com',
  signal: 'signal.org',
  skype: 'skype.com',
  imo: 'imo.im',
  zalo: 'zalo.me',
  likee: 'likee.video',
  bigo: 'bigo.tv',
  yalla: 'yalla.live',

  // Email & Productivity
  google: 'google.com',
  gmail: 'gmail.com',
  outlook: 'outlook.com',
  yahoo: 'yahoo.com',
  mailru: 'mail.ru',
  protonmail: 'proton.me',
  proton: 'proton.me',
  tutanota: 'tutanota.com',
  icloud: 'icloud.com',
  fastmail: 'fastmail.com',
  zoho: 'zoho.com',
  microsoft: 'microsoft.com',
  office365: 'office.com',

  // Tech & Dev
  github: 'github.com',
  gitlab: 'gitlab.com',
  bitbucket: 'bitbucket.org',
  firebase: 'firebase.google.com',
  aws: 'aws.amazon.com',
  azure: 'azure.microsoft.com',
  digitalocean: 'digitalocean.com',
  heroku: 'heroku.com',
  vercel: 'vercel.com',
  netlify: 'netlify.com',
  cloudflare: 'cloudflare.com',
  docker: 'docker.com',
  npm: 'npmjs.com',
  stackoverflow: 'stackoverflow.com',
  atlassian: 'atlassian.com',
  jira: 'jira.com',
  confluence: 'confluence.com',

  // Design & Creative
  adobe: 'adobe.com',
  canva: 'canva.com',
  figma: 'figma.com',
  sketch: 'sketch.com',
  invision: 'invisionapp.com',
  behance: 'behance.net',
  dribbble: 'dribbble.com',

  // Productivity & Collaboration
  notion: 'notion.so',
  trello: 'trello.com',
  asana: 'asana.com',
  monday: 'monday.com',
  clickup: 'clickup.com',
  slack: 'slack.com',
  zoom: 'zoom.us',
  teams: 'teams.microsoft.com',
  meet: 'meet.google.com',
  dropbox: 'dropbox.com',
  box: 'box.com',
  evernote: 'evernote.com',
  todoist: 'todoist.com',
  airtable: 'airtable.com',

  // Streaming & Entertainment
  netflix: 'netflix.com',
  spotify: 'spotify.com',
  hulu: 'hulu.com',
  hbo: 'hbomax.com',
  hbomax: 'hbomax.com',
  disney: 'disney.com',
  disneyplus: 'disneyplus.com',
  primevideo: 'primevideo.com',
  appletv: 'tv.apple.com',
  peacock: 'peacocktv.com',
  paramount: 'paramountplus.com',
  crunchyroll: 'crunchyroll.com',
  funimation: 'funimation.com',
  deezer: 'deezer.com',
  soundcloud: 'soundcloud.com',
  pandora: 'pandora.com',
  tidal: 'tidal.com',

  // Gaming
  steam: 'steampowered.com',
  epic: 'epicgames.com',
  epicgames: 'epicgames.com',
  origin: 'origin.com',
  ea: 'ea.com',
  ubisoft: 'ubisoft.com',
  blizzard: 'blizzard.com',
  battlenet: 'battle.net',
  roblox: 'roblox.com',
  minecraft: 'minecraft.net',
  playstation: 'playstation.com',
  xbox: 'xbox.com',
  nintendo: 'nintendo.com',
  faceit: 'faceit.com',
  esea: 'esea.net',
  esportal: 'esportal.com',

  // E-commerce & Retail
  amazon: 'amazon.com',
  ebay: 'ebay.com',
  etsy: 'etsy.com',
  shopify: 'shopify.com',
  walmart: 'walmart.com',
  target: 'target.com',
  bestbuy: 'bestbuy.com',
  aliexpress: 'aliexpress.com',
  alibaba: 'alibaba.com',
  wish: 'wish.com',
  shein: 'shein.com',
  shopee: 'shopee.com',
  lazada: 'lazada.com',
  mercadolibre: 'mercadolibre.com',
  flipkart: 'flipkart.com',
  wildberries: 'wildberries.ru',
  ozon: 'ozon.ru',
  avito: 'avito.ru',
  olx: 'olx.com',
  craigslist: 'craigslist.org',
  wayfair: 'wayfair.com',
  overstock: 'overstock.com',
  newegg: 'newegg.com',
  rakuten: 'rakuten.com',

  // Freelance & Work
  fiverr: 'fiverr.com',
  upwork: 'upwork.com',
  freelancer: 'freelancer.com',
  toptal: 'toptal.com',
  '99designs': '99designs.com',
  guru: 'guru.com',
  peopleperhour: 'peopleperhour.com',

  // Finance & Payments
  paypal: 'paypal.com',
  stripe: 'stripe.com',
  venmo: 'venmo.com',
  cashapp: 'cash.app',
  zelle: 'zellepay.com',
  wise: 'wise.com',
  transferwise: 'wise.com',
  revolut: 'revolut.com',
  n26: 'n26.com',
  chime: 'chime.com',

  // Crypto & Trading
  coinbase: 'coinbase.com',
  binance: 'binance.com',
  kraken: 'kraken.com',
  robinhood: 'robinhood.com',
  etrade: 'etrade.com',
  fidelity: 'fidelity.com',
  schwab: 'schwab.com',
  webull: 'webull.com',
  tradingview: 'tradingview.com',
  metatrader: 'metatrader4.com',
  fbs: 'fbs.com',
  exness: 'exness.com',
  xm: 'xm.com',
  iqoption: 'iqoption.com',
  expertoption: 'expertoption.com',
  olymptrade: 'olymptrade.com',
  pocket: 'pocketoption.com',
  pocketoption: 'pocketoption.com',
  quotex: 'quotex.io',
  deriv: 'deriv.com',
  binary: 'binary.com',

  // Dating
  tinder: 'tinder.com',
  bumble: 'bumble.com',
  hinge: 'hinge.co',
  match: 'match.com',
  okcupid: 'okcupid.com',
  pof: 'pof.com',
  badoo: 'badoo.com',
  happn: 'happn.com',
  coffee: 'coffeemeetsbagel.com',
  zoosk: 'zoosk.com',
  eharmony: 'eharmony.com',

  // Food Delivery
  doordash: 'doordash.com',
  grubhub: 'grubhub.com',
  ubereats: 'ubereats.com',
  instacart: 'instacart.com',
  postmates: 'postmates.com',
  seamless: 'seamless.com',
  deliveroo: 'deliveroo.com',
  wolt: 'wolt.com',
  glovo: 'glovoapp.com',
  rappi: 'rappi.com',
  swiggy: 'swiggy.com',
  zomato: 'zomato.com',
  foodpanda: 'foodpanda.com',
  fantuan: 'fantuan.ca',

  // Ride & Transport
  uber: 'uber.com',
  lyft: 'lyft.com',
  bolt: 'bolt.eu',
  didi: 'didiglobal.com',
  careem: 'careem.com',
  grab: 'grab.com',
  gojek: 'gojek.com',
  ola: 'olacabs.com',
  curb: 'gocurb.com',
  lime: 'li.me',
  bird: 'bird.co',

  // Travel & Hotels
  airbnb: 'airbnb.com',
  booking: 'booking.com',
  'booking.com': 'booking.com',
  expedia: 'expedia.com',
  hotels: 'hotels.com',
  vrbo: 'vrbo.com',
  agoda: 'agoda.com',
  tripadvisor: 'tripadvisor.com',
  kayak: 'kayak.com',
  skyscanner: 'skyscanner.com',
  priceline: 'priceline.com',
  hopper: 'hopper.com',

  // Fashion & Lifestyle
  nike: 'nike.com',
  adidas: 'adidas.com',
  zara: 'zara.com',
  hm: 'hm.com',
  uniqlo: 'uniqlo.com',
  asos: 'asos.com',
  nordstrom: 'nordstrom.com',
  macys: 'macys.com',
  sephora: 'sephora.com',
  ulta: 'ulta.com',

  // Food & Coffee
  starbucks: 'starbucks.com',
  dunkin: 'dunkindonuts.com',
  mcdonalds: 'mcdonalds.com',
  burgerking: 'bk.com',
  wendys: 'wendys.com',
  chipotle: 'chipotle.com',
  subway: 'subway.com',
  dominos: 'dominos.com',
  pizzahut: 'pizzahut.com',
  papajohns: 'papajohns.com',

  // Business & Tech
  apple: 'apple.com',
  samsung: 'samsung.com',
  huawei: 'huawei.com',
  xiaomi: 'mi.com',

  // ─── US Carriers ───
  att: 'att.com',
  'at&t': 'att.com',
  verizon: 'verizon.com',
  tmobile: 't-mobile.com',
  't-mobile': 't-mobile.com',
  sprint: 'sprint.com',
  visible: 'visible.com',
  cricket: 'cricketwireless.com',
  cricketmobile: 'cricketwireless.com',
  cricketwireless: 'cricketwireless.com',
  googlefi: 'fi.google.com',
  'google fi': 'fi.google.com',
  boost: 'boostmobile.com',
  boostmobile: 'boostmobile.com',
  metropcs: 'metrobyt-mobile.com',
  metropcsmobile: 'metrobyt-mobile.com',
  metrobytmobile: 'metrobyt-mobile.com',
  metro: 'metrobyt-mobile.com',
  metromobile: 'metrobyt-mobile.com',
  h2o: 'h2owireless.com',
  h2omobile: 'h2owireless.com',
  h2owireless: 'h2owireless.com',
  net10: 'net10wireless.com',
  net10mobile: 'net10wireless.com',
  net10wireless: 'net10wireless.com',
  tracfone: 'tracfone.com',
  tracfonemobile: 'tracfone.com',
  simplemobile: 'simplemobile.com',
  simple: 'simplemobile.com',
  simplemobilemobile: 'simplemobile.com',
  pageplus: 'pagepluscellular.com',
  pageplusmobile: 'pagepluscellular.com',
  pagepluscellular: 'pagepluscellular.com',
  ultramobile: 'ultramobile.com',
  ultra: 'ultramobile.com',
  straighttalk: 'straighttalk.com',
  straighttalkmobile: 'straighttalk.com',
  gosmart: 'gosmartmobile.com',
  gosmartmobile: 'gosmartmobile.com',
  republicwireless: 'republicwireless.com',
  ting: 'ting.com',
  usmobile: 'usmobile.com',
  mintmobile: 'mintmobile.com',
  redpocket: 'redpocket.com',
  redpocketmobile: 'redpocket.com',
  consumer: 'consumercellular.com',
  consumercellular: 'consumercellular.com',
  freedompop: 'freedompop.com',
  teflon: 'teflon.com',
  totalwireless: 'totalwireless.com',
  totalwirelessmobile: 'totalwireless.com',
  familymobile: 'myfamilymobile.com',
  walmartfamilymobile: 'myfamilymobile.com',
  goodmobile: 'good2gomobile.com',
  good2go: 'good2gomobile.com',
  good2gomobile: 'good2gomobile.com',
  puretalkusa: 'puretalkusa.com',
  puretalk: 'puretalkusa.com',
  textnow: 'textnow.com',
  credo: 'credomobile.com',
  credomobile: 'credomobile.com',

  // ─── UK Carriers ───
  vodafone: 'vodafone.com',
  ee: 'ee.co.uk',
  three: 'three.co.uk',
  o2: 'o2.co.uk',
  giffgaff: 'giffgaff.com',
  tesco: 'tescomobile.com',
  tescomobile: 'tescomobile.com',
  sky: 'sky.com',
  skymobile: 'sky.com',
  bt: 'bt.com',
  btmobile: 'bt.com',
  talkmobile: 'talkmobile.co.uk',
  idmobile: 'idmobile.co.uk',
  voxi: 'voxi.co.uk',
  smarty: 'smarty.co.uk',
  asda: 'asdamobile.co.uk',
  asdamobile: 'asdamobile.co.uk',

  // ─── Canada Carriers ───
  rogers: 'rogers.com',
  bell: 'bell.ca',
  bellmobility: 'bell.ca',
  telus: 'telus.com',
  fido: 'fido.ca',
  koodo: 'koodomobile.com',
  koodomobile: 'koodomobile.com',
  virgin: 'virginplus.ca',
  virginmobile: 'virginplus.ca',
  virginplus: 'virginplus.ca',
  chatr: 'chatrmobile.com',
  chatrmobile: 'chatrmobile.com',
  publicmobile: 'publicmobile.ca',
  freedommobile: 'freedommobile.ca',
  lucky: 'luckymobile.ca',
  luckymobile: 'luckymobile.ca',
  sasktel: 'sasktel.com',

  // ─── Europe Carriers ───
  orange: 'orange.com',
  sfr: 'sfr.fr',
  bouygues: 'bouyguestelecom.fr',
  bouyguestelecom: 'bouyguestelecom.fr',
  free: 'free.fr',
  freemobile: 'free.fr',
  deutschetelekom: 'telekom.de',
  telekom: 'telekom.de',
  congstar: 'congstar.de',
  aldi: 'alditalk.de',
  alditalk: 'alditalk.de',
  o2de: 'o2online.de',
  blau: 'blau.de',
  tim: 'tim.it',
  windtre: 'windtre.it',
  wind: 'windtre.it',
  iliad: 'iliad.it',
  kpn: 'kpn.com',
  tele2: 'tele2.com',
  proximus: 'proximus.be',
  base: 'base.be',
  swisscom: 'swisscom.ch',
  sunrise: 'sunrise.ch',
  salt: 'salt.ch',
  a1: 'a1.net',
  magenta: 'magenta.at',
  play: 'play.pl',
  plus: 'plus.pl',
  polkomtel: 'plus.pl',
  tmobilepl: 't-mobile.pl',
  yettel: 'yettel.hu',
  turkcell: 'turkcell.com.tr',
  turktelekom: 'turktelekom.com.tr',
  avea: 'turktelekom.com.tr',
  lifecell: 'lifecell.ua',
  kyivstar: 'kyivstar.ua',
  mts: 'mts.ru',
  megafon: 'megafon.ru',
  beeline: 'beeline.ru',
  yota: 'yota.ru',
  tele2ru: 'tele2.ru',
  teliasonera: 'telia.se',
  telia: 'telia.se',
  telenor: 'telenor.com',
  dna: 'dna.fi',
  elisa: 'elisa.fi',
  tdc: 'tdc.dk',
  '3dk': 'tre.dk',
  ice: 'ice.no',
  comviq: 'comviq.se',
  hallon: 'hallon.se',
  halebop: 'halebop.se',
  tmobilecz: 't-mobile.cz',
  o2cz: 'o2.cz',
  cosmote: 'cosmote.gr',
  nova: 'nova.gr',
  nos: 'nos.pt',
  meo: 'meo.pt',
  yoigo: 'yoigo.com',
  masmovil: 'masmovil.com',

  // ─── Latin America Carriers ───
  claro: 'claro.com.br',
  movistar: 'movistar.com',
  telcel: 'telcel.com',
  digicel: 'digicelgroup.com',
  entel: 'entel.cl',
  wom: 'wom.cl',
  personal: 'personal.com.ar',
  tigo: 'tigo.com',
  bitel: 'bitel.com.pe',
  vivo: 'vivo.com.br',
  oi: 'oi.com.br',
  nextel: 'nextel.com.br',
  unefon: 'unefon.com.mx',
  altice: 'altice.com.do',
  kolbi: 'kolbi.cr',
  tuenti: 'tuenti.com',
  digitel: 'digitel.com.ve',
  cnt: 'cnt.gob.ec',

  // ─── Asia Carriers ───
  airtel: 'airtel.in',
  jio: 'jio.com',
  bsnl: 'bsnl.co.in',
  vi: 'myvi.in',
  vodafoneidea: 'myvi.in',
  idea: 'myvi.in',
  globe: 'globe.com.ph',
  smart: 'smart.com.ph',
  smartcommunications: 'smart.com.ph',
  dito: 'dito.ph',
  singtel: 'singtel.com',
  starhub: 'starhub.com',
  m1: 'm1.com.sg',
  celcom: 'celcom.com.my',
  maxis: 'maxis.com.my',
  digi: 'digi.com.my',
  umobile: 'u.com.my',
  dtac: 'dtac.co.th',
  ais: 'ais.th',
  true: 'true.th',
  truemove: 'true.th',
  dialog: 'dialog.lk',
  grameenphone: 'grameenphone.com',
  robi: 'robi.com.bd',
  banglalink: 'banglalink.net',
  ncell: 'ncell.axiata.com',
  smartfren: 'smartfren.com',
  indosat: 'indosatooredoo.com',
  xl: 'xl.co.id',
  xlaxiata: 'xl.co.id',
  telkomsel: 'telkomsel.com',
  tri: 'tri.co.id',
  chinamobile: 'chinamobile.com',
  chinaunicom: 'chinaunicom.com',
  chinatelecom: 'chinatelecom.com.cn',
  kddi: 'kddi.com',
  au: 'au.com',
  softbank: 'softbank.jp',
  nttdocomo: 'docomo.ne.jp',
  docomo: 'docomo.ne.jp',
  skt: 'sktelecom.com',
  kt: 'kt.com',
  lgu: 'uplus.co.kr',
  lguplus: 'uplus.co.kr',
  viettel: 'viettel.com.vn',
  mobifone: 'mobifone.vn',
  vinaphone: 'vinaphone.com.vn',
  smartone: 'smartone.com',
  csl: 'hkcsl.com',
  pccw: 'pccw.com',
  chunghwa: 'cht.com.tw',
  taiwanmobile: 'taiwanmobile.com',
  fareastone: 'fetnet.net',

  // ─── Middle East Carriers ───
  etisalat: 'etisalat.ae',
  du: 'du.ae',
  stc: 'stc.com.sa',
  mobily: 'mobily.com.sa',
  zain: 'zain.com',
  ooredoo: 'ooredoo.com',
  batelco: 'batelco.com',
  omantel: 'omantel.om',
  asiacell: 'asiacell.com',
  korek: 'korektel.com',
  jawwal: 'jawwal.ps',
  wataniya: 'wataniya.ps',
  touch: 'touch.com.lb',
  alfa: 'alfa.com.lb',
  syriatel: 'syriatel.sy',
  yemenmobile: 'yemenmobile.com.ye',

  // ─── Africa Carriers ───
  safaricom: 'safaricom.co.ke',
  mtn: 'mtn.com',
  glo: 'gloworld.com',
  '9mobile': '9mobile.com.ng',
  airtelng: 'airtel.com.ng',
  airteltigo: 'airteltigo.com.gh',
  vodacom: 'vodacom.co.za',
  cellc: 'cellc.co.za',
  rain: 'rain.co.za',
  telkom: 'telkom.co.za',
  telkomsa: 'telkom.co.za',
  orange: 'orange.com',
  maroctelecom: 'iam.ma',
  inwi: 'inwi.ma',
  tunisietelecom: 'tunisietelecom.tn',
  moov: 'moov.com',
  togocel: 'togocel.tg',
  expresso: 'expressotelecom.com',
  econet: 'econet.co.zw',
  mascom: 'mascom.bw',
  zamtel: 'zamtel.co.zm',
  smile: 'smile.com.ng',
  ntel: 'ntel.com.ng',
  halotel: 'halotel.co.tz',
  zantel: 'zantel.co.tz',
  tigo: 'tigo.com',
  africell: 'africell.com',

  // ─── Oceania Carriers ───
  optus: 'optus.com.au',
  telstra: 'telstra.com.au',
  vodafoneau: 'vodafone.com.au',
  spark: 'spark.co.nz',
  vodafonenz: 'vodafone.co.nz',
  twodegrees: '2degrees.nz',
  '2degrees': '2degrees.nz',

  // ─── MVNO & Others ───
  lycamobile: 'lycamobile.com',
  lebara: 'lebara.com',
  cubacel: 'etecsa.cu',

  // Misc Services
  yelp: 'yelp.com',
  yandex: 'yandex.com',
  naver: 'naver.com',
  baidu: 'baidu.com',
  momo: 'momo.vn',
  yohoho: 'yohoho.io',
  yippi: 'yippi.biz',

  // News & Media
  nytimes: 'nytimes.com',
  washingtonpost: 'washingtonpost.com',
  bbc: 'bbc.com',
  cnn: 'cnn.com',
  forbes: 'forbes.com',
  bloomberg: 'bloomberg.com',
  reuters: 'reuters.com',
  medium: 'medium.com',
  substack: 'substack.com',

  // Health & Fitness
  myfitnesspal: 'myfitnesspal.com',
  strava: 'strava.com',
  fitbit: 'fitbit.com',
  peloton: 'onepeloton.com',
  headspace: 'headspace.com',
  calm: 'calm.com',
  noom: 'noom.com',

  // Education
  coursera: 'coursera.org',
  udemy: 'udemy.com',
  udacity: 'udacity.com',
  skillshare: 'skillshare.com',
  linkedinlearning: 'linkedin.com',
  duolingo: 'duolingo.com',
  khan: 'khanacademy.org',
  edx: 'edx.org',

  // Gift Cards & Rewards
  egifter: 'egifter.com',
  giftcards: 'giftcards.com',
  fetchrewards: 'fetchrewards.com',
  ibotta: 'ibotta.com',
  swagbucks: 'swagbucks.com',
  erewards: 'e-rewards.com',

  // Gaming Platforms & Stores
  eneba: 'eneba.com',
  g2a: 'g2a.com',
  kinguin: 'kinguin.net',
  fanatical: 'fanatical.com',
  humblebundle: 'humblebundle.com',
  gog: 'gog.com',
  greenmangaming: 'greenmangaming.com',
  epicnpc: 'epicnpc.com',

  // Russian Services
  faberlic: 'faberlic.com',

  // Asian Services
  tokopedia: 'tokopedia.com',
  bukalapak: 'bukalapak.com',
  jdcom: 'jd.com',
  pinduoduo: 'pinduoduo.com',

  // Latin America
  mercadopago: 'mercadopago.com',
  nubank: 'nubank.com.br',
  picpay: 'picpay.com',

  // Misc popular services from OTP providers
  finishline: 'finishline.com',
  fedex: 'fedex.com',
  ups: 'ups.com',
  usps: 'usps.com',
  dhl: 'dhl.com',

  // More OTP services from SMSPool/5sim
  '1688': '1688.com',
  '1xbet': '1xbet.com',
  '1q': '1q.com',
  '1stopmove': '1stopmove.com',
  '2dehands': '2dehands.be',
  '2game': '2game.com',
  '2redbeans': '2redbeans.com',
  '3fun': '3fun.co',
  '360nrs': '360nrs.com',
  '5ka': '5ka.ru',
  '5karu': '5ka.ru',
  '5miles': '5miles.com',
  '7eleven': '7-eleven.com',
  '7mall': '7-mall.com',
  '888poker': '888poker.com',
  aarprewards: 'aarp.org',
  aarp: 'aarp.org',
  aarpreward: 'aarp.org',
  aditup: 'aditup.com',
  alignable: 'alignable.com',
  allset: 'allsetnow.com',
  altbalaji: 'altbalaji.com',
  amasia: 'amasia.vc',
  adlist24: 'adlist24.dk',
  afreecatv: 'afreecatv.com',
  airtel: 'airtel.in',
  alipay: 'alipay.com',
  allegro: 'allegro.pl',
  alphapofitness: 'alphapofitness.com',
  amex: 'americanexpress.com',
  americanexpress: 'americanexpress.com',
  any: 'any.do',
  aol: 'aol.com',
  aparat: 'aparat.com',
  apteka: 'apteka.ru',
  atom: 'atom.com',
  avon: 'avon.com',
  band: 'band.us',
  bankofamerica: 'bankofamerica.com',
  beget: 'beget.com',
  bershka: 'bershka.com',
  bet365: 'bet365.com',
  betfair: 'betfair.com',
  betway: 'betway.com',
  bitfinex: 'bitfinex.com',
  bitmex: 'bitmex.com',
  blablacar: 'blablacar.com',
  blockchain: 'blockchain.com',
  blued: 'blued.com',
  borderlinx: 'borderlinx.com',
  brawlstars: 'brawlstars.com',
  bybit: 'bybit.com',
  caixa: 'caixa.gov.br',
  capital: 'capital.com',
  carousell: 'carousell.com',
  cdkeys: 'cdkeys.com',
  chanel: 'chanel.com',
  chase: 'chase.com',
  citimobile: 'citibank.com',
  citibank: 'citibank.com',
  cliqq: 'cliqq.net',
  clover: 'clover.com',
  cmc: 'coinmarketcap.com',
  coinmarketcap: 'coinmarketcap.com',
  coinsph: 'coins.ph',
  colourpop: 'colourpop.com',
  crypto: 'crypto.com',
  cryptocom: 'crypto.com',
  damai: 'damai.cn',
  dent: 'dentwireless.com',
  dhgate: 'dhgate.com',
  dingdong: 'dingdong.com',
  directv: 'directv.com',
  dodo: 'dodopoint.com',
  dodopizza: 'dodopizza.ru',
  drom: 'drom.ru',
  dundle: 'dundle.com',
  ecwid: 'ecwid.com',
  eloot: 'eloot.gg',
  elootgg: 'eloot.gg',
  engagespark: 'engagespark.com',
  eobot: 'eobot.com',
  esendex: 'esendex.com',
  espressohouse: 'espressohouse.com',
  europym: 'europym.eu',
  everyoneapi: 'everyoneapi.com',
  eyecon: 'eyecon.com',
  fanatics: 'fanatics.com',
  fanduel: 'fanduel.com',
  fantasy: 'fantasy.top',
  fave: 'myfave.com',
  fetlife: 'fetlife.com',
  figureeight: 'appen.com',
  filimo: 'filimo.com',
  findmate: 'findmate.com',
  firstrade: 'firstrade.com',
  fivesim: '5sim.net',
  fizz: 'fizz.ca',
  flexiroam: 'flexiroam.com',
  footlocker: 'footlocker.com',
  fortnite: 'fortnite.com',
  foursquare: 'foursquare.com',
  freepik: 'freepik.com',
  freecharge: 'freecharge.in',
  freetrade: 'freetrade.io',
  freshworks: 'freshworks.com',
  ftx: 'ftx.com',
  fullerton: 'fullertonhealthcare.com',
  gamivo: 'gamivo.com',
  gate: 'gate.io',
  gateio: 'gate.io',
  gcash: 'gcash.com',
  gemini: 'gemini.com',
  genshin: 'genshin.hoyoverse.com',
  getir: 'getir.com',
  getresponse: 'getresponse.com',
  globo: 'globo.com',
  gmx: 'gmx.com',
  godaddy: 'godaddy.com',
  gopay: 'gopay.co.id',
  grabfood: 'grab.com',
  groupon: 'groupon.com',
  gumtree: 'gumtree.com',
  haraj: 'haraj.com.sa',
  hashkey: 'hashkey.com',
  hepsiburada: 'hepsiburada.com',
  hi5: 'hi5.com',
  hilton: 'hilton.com',
  hktvmall: 'hktvmall.com',
  honkai: 'honkaiimpact3.hoyoverse.com',
  hotmail: 'hotmail.com',
  hotpads: 'hotpads.com',
  houzz: 'houzz.com',
  hsbc: 'hsbc.com',
  huobi: 'huobi.com',
  hyperwallet: 'hyperwallet.com',
  icecom: 'ice.com',
  icici: 'icicibank.com',
  ifood: 'ifood.com.br',
  imgur: 'imgur.com',
  immoweb: 'immoweb.be',
  immowelt: 'immowelt.de',
  indodax: 'indodax.com',
  indriver: 'indriver.com',
  ing: 'ing.com',
  interac: 'interac.ca',
  iqos: 'iqos.com',
  irctc: 'irctc.co.in',
  jcpenney: 'jcpenney.com',
  jdid: 'jdid.com',
  jetbrains: 'jetbrains.com',
  jimdo: 'jimdo.com',
  jio: 'jio.com',
  joom: 'joom.com',
  justeat: 'just-eat.com',
  kfc: 'kfc.com',
  klarna: 'klarna.com',
  kucoin: 'kucoin.com',
  kwai: 'kwai.com',
  lalamove: 'lalamove.com',
  leboncoin: 'leboncoin.fr',
  lenovo: 'lenovo.com',
  letgo: 'letgo.com',
  lifesum: 'lifesum.com',
  livecoin: 'livecoin.net',
  livejournal: 'livejournal.com',
  loco: 'loco.gg',
  loft: 'loft.com.br',
  lottevipshop: 'lotteon.com',
  lovoo: 'lovoo.com',
  lulumon: 'lululemon.com',
  lululemon: 'lululemon.com',
  magalu: 'magazineluiza.com.br',
  mailchimp: 'mailchimp.com',
  mailgun: 'mailgun.com',
  marktplaats: 'marktplaats.nl',
  marriott: 'marriott.com',
  mastercard: 'mastercard.com',
  maxim: 'taximaxim.com',
  megafon: 'megafon.ru',
  meitu: 'meitu.com',
  mercado: 'mercadolibre.com',
  metamask: 'metamask.io',
  mexc: 'mexc.com',
  mihoyo: 'mihoyo.com',
  minted: 'minted.com',
  mintmobile: 'mintmobile.com',
  moomoo: 'moomoo.com',
  moonpig: 'moonpig.com',
  mpesa: 'safaricom.co.ke',
  mtn: 'mtn.com',
  mts: 'mts.ru',
  myntra: 'myntra.com',
  namecheap: 'namecheap.com',
  nba: 'nba.com',
  nexon: 'nexon.com',
  nexus: 'nexusmods.com',
  niki: 'niki.ai',
  ning: 'ning.com',
  niuke: 'nowcoder.com',
  noon: 'noon.com',
  nordvpn: 'nordvpn.com',
  nvidia: 'nvidia.com',
  okex: 'okx.com',
  okx: 'okx.com',
  onetrust: 'onetrust.com',
  onlyfans: 'onlyfans.com',
  opensea: 'opensea.io',
  orange: 'orange.com',
  otp: 'otpbank.hu',
  paddle: 'paddle.com',
  pagseguro: 'pagseguro.uol.com.br',
  panda: 'foodpanda.com',
  parler: 'parler.com',
  patreon: 'patreon.com',
  paycell: 'paycell.com.tr',
  payeer: 'payeer.com',
  payme: 'payme.uz',
  paymob: 'paymob.com',
  payoneer: 'payoneer.com',
  paysafecard: 'paysafecard.com',
  paytm: 'paytm.com',
  payza: 'payza.com',
  pedidosya: 'pedidosya.com',
  peoplematters: 'peoplematters.in',
  pepsi: 'pepsi.com',
  perfectmoney: 'perfectmoney.com',
  periscope: 'periscope.tv',
  phonepe: 'phonepe.com',
  picuki: 'picuki.com',
  pix: 'pix.com.br',
  plaid: 'plaid.com',
  plex: 'plex.tv',
  pling: 'pling.de',
  pluralsight: 'pluralsight.com',
  pokerstars: 'pokerstars.com',
  poloniex: 'poloniex.com',
  poshmark: 'poshmark.com',
  probit: 'probit.com',
  propertyguru: 'propertyguru.com',
  propertypal: 'propertypal.com',
  prosus: 'prosus.com',
  pubg: 'pubg.com',
  publix: 'publix.com',
  puma: 'puma.com',
  puregym: 'puregym.com',
  qiwi: 'qiwi.com',
  quora: 'quora.com',
  radissonhotels: 'radissonhotels.com',
  ralphs: 'ralphs.com',
  razorpay: 'razorpay.com',
  redfin: 'redfin.com',
  rediffmail: 'rediff.com',
  reebok: 'reebok.com',
  resy: 'resy.com',
  retool: 'retool.com',
  ring: 'ring.com',
  ritual: 'ritual.co',
  robokassa: 'robokassa.com',
  rocketleague: 'rocketleague.com',
  royalgames: 'royalgames.com',
  rumble: 'rumble.com',
  safeway: 'safeway.com',
  sainsburys: 'sainsburys.co.uk',
  samsclub: 'samsclub.com',
  sanook: 'sanook.com',
  santander: 'santander.com',
  scout24: 'scout24.de',
  scribd: 'scribd.com',
  seatgeek: 'seatgeek.com',
  sendgrid: 'sendgrid.com',
  sendinblue: 'sendinblue.com',
  shopclues: 'shopclues.com',
  shoprite: 'shoprite.com',
  shutterfly: 'shutterfly.com',
  sisal: 'sisal.it',
  skrill: 'skrill.com',
  skyeng: 'skyeng.ru',
  skyescorts: 'skyescorts.com',
  skysports: 'skysports.com',
  smartcat: 'smartcat.com',
  snapdeal: 'snapdeal.com',
  snkrs: 'nike.com',
  sofi: 'sofi.com',
  solana: 'solana.com',
  souq: 'amazon.sa',
  spareroom: 'spareroom.co.uk',
  splitwise: 'splitwise.com',
  sportmaster: 'sportmaster.ru',
  squareup: 'squareup.com',
  squarespace: 'squarespace.com',
  stacksocial: 'stacksocial.com',
  stockx: 'stockx.com',
  stoiximan: 'stoiximan.gr',
  stubhub: 'stubhub.com',
  supercell: 'supercell.com',
  sweatcoin: 'sweatco.in',
  sweetwater: 'sweetwater.com',
  swvl: 'swvl.com',
  syfe: 'syfe.com',
  taobao: 'taobao.com',
  tasker: 'taskrabbit.com',
  taskrabbit: 'taskrabbit.com',
  taxfix: 'taxfix.de',
  teamviewer: 'teamviewer.com',
  telekom: 'telekom.de',
  tencent: 'tencent.com',
  tesco: 'tesco.com',
  tescobank: 'tescobank.com',
  thredup: 'thredup.com',
  tiendamia: 'tiendamia.com',
  tiki: 'tiki.vn',
  tikona: 'tikona.in',
  tile: 'thetileapp.com',
  timhortons: 'timhortons.com',
  tmall: 'tmall.com',
  tokko: 'tokko.com',
  toss: 'toss.im',
  transfergo: 'transfergo.com',
  trendyol: 'trendyol.com',
  truebalance: 'truebalance.io',
  truecaller: 'truecaller.com',
  tumblr: 'tumblr.com',
  turbotax: 'turbotax.intuit.com',
  tvn: 'tvn24.pl',
  twebmall: 'tweb.co.za',
  twilio: 'twilio.com',
  ubank: 'ubank.com.au',
  udaan: 'udaan.com',
  ufc: 'ufc.com',
  uklon: 'uklon.com.ua',
  unibet: 'unibet.com',
  united: 'united.com',
  unity: 'unity.com',
  uphold: 'uphold.com',
  uppaal: 'uppaal.org',
  valorant: 'playvalorant.com',
  vechain: 'vechain.org',
  viator: 'viator.com',
  vinted: 'vinted.com',
  virgin: 'virgin.com',
  visa: 'visa.com',
  vivaldi: 'vivaldi.com',
  vivino: 'vivino.com',
  vivo: 'vivo.com',
  vivastreet: 'vivastreet.com',
  vkusvill: 'vkusvill.ru',
  vons: 'vons.com',
  vova: 'vova.com',
  vultr: 'vultr.com',
  walmartmoneycard: 'walmartmoneycard.com',
  warframe: 'warframe.com',
  wargaming: 'wargaming.net',
  webex: 'webex.com',
  webmoney: 'webmoney.ru',
  wellsfargo: 'wellsfargo.com',
  westernunion: 'westernunion.com',
  whatsaround: 'whatsaround.com',
  whatnot: 'whatnot.com',
  whopper: 'bk.com',
  winamax: 'winamax.com',
  windtre: 'windtre.it',
  wink: 'wink.org',
  wirex: 'wirexapp.com',
  wix: 'wix.com',
  wizzair: 'wizzair.com',
  worldremit: 'worldremit.com',
  wrike: 'wrike.com',
  wunderlist: 'wunderlist.com',
  xfinity: 'xfinity.com',
  xiaohongshu: 'xiaohongshu.com',
  xoom: 'xoom.com',
  yad2: 'yad2.co.il',
  yamibuy: 'yamibuy.com',
  yesbank: 'yesbank.in',
  yili: 'yili.com',
  yolo: 'yolo.money',
  youla: 'youla.ru',
  youporn: 'youporn.com',
  ytmusic: 'music.youtube.com',
  zapier: 'zapier.com',
  zeek: 'zeek.me',
  zerodha: 'zerodha.com',
  zillow: 'zillow.com',
  zoopla: 'zoopla.co.uk',
  zynga: 'zynga.com',

  // Add variations and common misspellings
  insta: 'instagram.com',
  fb: 'facebook.com',
  yt: 'youtube.com',
  goog: 'google.com',
  googl: 'google.com',
  amzn: 'amazon.com',
  msft: 'microsoft.com',
  appl: 'apple.com',
  wa: 'whatsapp.com',
  tg: 'telegram.org',
}

// Get first letter as fallback
function getInitial(name: string): string {
  return name.charAt(0).toUpperCase()
}

// Generate a consistent color based on the service name
function getColorFromName(name: string): string {
  const colors = [
    '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7',
    '#DDA0DD', '#98D8C8', '#F7DC6F', '#BB8FCE', '#85C1E9',
    '#F8B500', '#00CED1', '#FF69B4', '#32CD32', '#FF4500',
    '#9370DB', '#20B2AA', '#FFD700', '#00FA9A', '#DC143C',
  ]

  let hash = 0
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash)
  }

  return colors[Math.abs(hash) % colors.length]
}

function getServiceDomain(serviceName: string): string | null {
  const normalized = serviceName.toLowerCase().replace(/[^a-z0-9]/g, '')
  const withDots = serviceName.toLowerCase().replace(/\s+/g, '')

  // 1. Direct match in our known domains
  if (SERVICE_DOMAINS[normalized]) {
    return SERVICE_DOMAINS[normalized]
  }

  // 2. Try with dots preserved (e.g., "booking.com")
  if (SERVICE_DOMAINS[withDots]) {
    return SERVICE_DOMAINS[withDots]
  }

  // 3. Try splitting by spaces and matching individual words
  // This handles "Google Firebase" -> check "google" then "firebase"
  const words = serviceName.toLowerCase().split(/\s+/)
  for (const word of words) {
    const cleanWord = word.replace(/[^a-z0-9]/g, '')
    if (cleanWord.length >= 2 && SERVICE_DOMAINS[cleanWord]) {
      return SERVICE_DOMAINS[cleanWord]
    }
  }

  // Don't do fuzzy/partial matching - it causes too many false positives
  // (e.g., "2RedBeans" incorrectly matching "ea" -> ea.com)
  return null
}

export default function ServiceLogo({ name, size = 32, className = '' }: ServiceLogoProps) {
  const [imgSrc, setImgSrc] = useState<string | null>(null)
  const [loadFailed, setLoadFailed] = useState(false)
  const [loadAttempt, setLoadAttempt] = useState(0)

  const domain = getServiceDomain(name)
  const initial = getInitial(name)
  const bgColor = getColorFromName(name)

  useEffect(() => {
    // Reset state when name changes
    setLoadFailed(false)
    setLoadAttempt(0)

    if (domain) {
      // Start with Clearbit
      setImgSrc(`https://logo.clearbit.com/${domain}`)
    } else {
      // No known domain, use letter avatar
      setLoadFailed(true)
    }
  }, [name, domain])

  // Fallback chain: Clearbit -> Google -> DuckDuckGo -> Favicon.ico direct -> Gradient
  const handleError = () => {
    if (loadAttempt === 0 && domain) {
      // Clearbit failed, try Google Favicons
      setLoadAttempt(1)
      setImgSrc(`https://www.google.com/s2/favicons?domain=${domain}&sz=128`)
    } else if (loadAttempt === 1 && domain) {
      // Google failed or generic, try DuckDuckGo
      setLoadAttempt(2)
      setImgSrc(`https://icons.duckduckgo.com/ip3/${domain}.ico`)
    } else if (loadAttempt === 2 && domain) {
      // DuckDuckGo failed or generic, try direct favicon.ico
      setLoadAttempt(3)
      setImgSrc(`https://${domain}/favicon.ico`)
    } else if (loadAttempt === 3 && domain) {
      // Direct favicon failed, try Yandex (good for international sites)
      setLoadAttempt(4)
      setImgSrc(`https://favicon.yandex.net/favicon/${domain}`)
    } else {
      // All sources failed, use gradient letter avatar
      setLoadFailed(true)
    }
  }

  const handleLoad = (e: React.SyntheticEvent<HTMLImageElement>) => {
    // Accept any loaded image - we've already tried to get the best source
    // Size-based detection was too aggressive and rejected valid favicons
    // (Many legitimate logos like WhatsApp, 7-Eleven are 32x32 or smaller)
  }

  // Show letter avatar if no domain or all load attempts failed
  if (loadFailed || !imgSrc) {
    return (
      <div
        className={`flex items-center justify-center rounded-lg font-bold text-white ${className}`}
        style={{
          width: size,
          height: size,
          backgroundColor: bgColor,
          fontSize: size * 0.5,
        }}
      >
        {initial}
      </div>
    )
  }

  return (
    <div
      className={`relative bg-white rounded-lg overflow-hidden flex items-center justify-center ${className}`}
      style={{ width: size, height: size }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={imgSrc}
        alt={name}
        width={size - 4}
        height={size - 4}
        className="object-contain"
        onError={handleError}
        onLoad={handleLoad}
        loading="lazy"
        style={{ maxWidth: size - 4, maxHeight: size - 4 }}
      />
    </div>
  )
}
