import { Product, Category, NavItem } from './types'

export const navCategories: NavItem[] = [
  { label: 'Scripts', href: '/scripts' },
  { label: 'Virtual Numbers', href: '/virtual-numbers' },
  { label: 'eSIMs', href: '/esim' },
  { label: 'Cards', href: '/cards' },
  { label: 'Gift Cards', href: '/gift-cards' },
  { label: 'Blog', href: '/blog' },
]

export const recommendedProducts: Product[] = [
  {
    id: '1',
    name: 'Python Automation Script',
    slug: 'python-automation-script',
    description: 'Automate your workflow with Python',
    price: 80,
    rating: 5,
    reviewCount: 124,
    category: 'Scripts',
    icon: 'terminal',
    iconColor: 'yellow',
    tags: ['Python', 'Automation'],
    badge: 'KSU',
  },
  {
    id: '2',
    name: 'Global eSIM (10GB)',
    slug: 'global-esim-10gb',
    description: 'Stay connected worldwide',
    price: 25,
    rating: 5,
    reviewCount: 89,
    category: 'eSIMs',
    icon: 'globe',
    iconColor: 'green',
    tags: ['eSIM', 'Global'],
    badge: 'HOT',
  },
  {
    id: '3',
    name: 'Cloud Database Helper',
    slug: 'cloud-database-helper',
    description: 'Manage your cloud databases',
    price: 45,
    rating: 5,
    reviewCount: 56,
    category: 'Tools',
    icon: 'database',
    iconColor: 'blue',
    tags: ['Database', 'Cloud'],
    badge: 'KSU',
  },
  {
    id: '4',
    name: 'AI Analysis Suite',
    slug: 'ai-analysis-suite',
    description: 'AI-powered analytics tools',
    price: 120,
    rating: 5,
    reviewCount: 34,
    category: 'Tools',
    icon: 'sparkles',
    iconColor: 'purple',
    tags: ['AI', 'Analytics'],
    badge: 'NEW',
  },
]

export const popularProducts: Product[] = [
  {
    id: '5',
    name: 'Automated Trading Bot',
    slug: 'automated-trading-bot',
    description: 'Automated crypto trading',
    price: 100,
    priceRange: { min: 100, max: 500 },
    rating: 5,
    reviewCount: 234,
    category: 'Scripts',
    icon: 'chart',
    iconColor: 'orange',
    tags: ['Trading', 'Crypto'],
  },
  {
    id: '6',
    name: 'European eSIM Pro',
    slug: 'european-esim-pro',
    description: 'European coverage eSIM',
    price: 25,
    priceRange: { min: 25, max: 45 },
    rating: 5,
    reviewCount: 189,
    category: 'eSIMs',
    icon: 'globe',
    iconColor: 'green',
    tags: ['eSIM', 'Europe'],
  },
  {
    id: '7',
    name: 'Private VIP Numbers',
    slug: 'private-vip-numbers',
    description: 'Premium virtual numbers',
    price: 15,
    priceRange: { min: 15, max: 30 },
    rating: 5,
    reviewCount: 156,
    category: 'Virtual Numbers',
    icon: 'wifi',
    iconColor: 'indigo',
    tags: ['Numbers', 'VIP'],
  },
  {
    id: '8',
    name: 'SEO Optimization Tool',
    slug: 'seo-optimization-tool',
    description: 'Boost your SEO rankings',
    price: 40,
    priceRange: { min: 40, max: 120 },
    rating: 5,
    reviewCount: 98,
    category: 'Tools',
    icon: 'sparkles',
    iconColor: 'primary',
    tags: ['SEO', 'Marketing'],
  },
]

export const scriptProducts: Product[] = [
  {
    id: '9',
    name: 'Python Automation Suite',
    slug: 'python-automation-suite',
    description: 'Complete automation toolkit',
    price: 49,
    priceRange: { min: 49, max: 120 },
    rating: 5,
    reviewCount: 124,
    category: 'Automation',
    icon: 'terminal',
    iconColor: 'orange',
    tags: ['Python'],
    badge: 'HOT',
    images: [
      { url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvwgfYMEvcI_nX3811VEyCy34SMnKHy9dmdnqG3nSMOUjjKLHrwM1Buu7vIN4sHUv_IHj3lxtx8AuvVgtQJrjdBjilef-qD6NbH3AMwpj-xP3Cl3XD4r8kxRx3ZJzJe8Y-Z4MqVrZdrhg60-dWHm_iNTlUzZhPqmEvucOUsNN2Cqq1nlRE-lUiK6PR4GpN2-YM32iXvk86ERNf_KfTr8v3fkU0u395JRo_hw-hlhfenuygiypi5Pyn0V13zGizBFBqXGrkP8TTlHSx', isPrimary: true },
    ],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvwgfYMEvcI_nX3811VEyCy34SMnKHy9dmdnqG3nSMOUjjKLHrwM1Buu7vIN4sHUv_IHj3lxtx8AuvVgtQJrjdBjilef-qD6NbH3AMwpj-xP3Cl3XD4r8kxRx3ZJzJe8Y-Z4MqVrZdrhg60-dWHm_iNTlUzZhPqmEvucOUsNN2Cqq1nlRE-lUiK6PR4GpN2-YM32iXvk86ERNf_KfTr8v3fkU0u395JRo_hw-hlhfenuygiypi5Pyn0V13zGizBFBqXGrkP8TTlHSx',
    seller: {
      id: 's1',
      name: 'DevStudio Pro',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGUCLNWcUo0J-ozj8dZhQWGNJOY4ZTHR9607k1ISKsm9ponmbT6D1HqmngWq_ba6QcYc4gUb27RXhWseOvh2s76qiCa30rOvZSm6Y0WiLIj6F-Hc5idHj4aKadRxrDH5qUlIWq5P08AbAyu2b5oUiYY7odzt8AnYIcFkip_65tGErCzVJjRd_tF26tNDlL2JFVY65qGxch9uZpjjllyEkce4irYdD84-kAlxNCc4dgtWuY0nLVsUEjQZRm8loC14Dv96iyGK-WsH4M',
      verified: true,
      badge: 'Top Seller',
    },
    features: [
      { icon: 'flash', title: 'High Performance', description: 'Asynchronous I/O processing for maximum efficiency and speed.' },
      { icon: 'shield', title: 'Secure by Design', description: 'Built-in encryption, credential management, and security protocols.' },
      { icon: 'settings', title: 'Easy Configuration', description: 'Simple YAML-based configuration for quick setup and deployment.' },
      { icon: 'cloud', title: 'Cloud Ready', description: 'Seamless integration with AWS, Google Cloud, and Azure services.' },
    ],
    specs: [
      { label: 'Language', value: 'Python 3.10+' },
      { label: 'Dependencies', value: 'Pandas, Scrapy, Selenium, PyYAML' },
      { label: 'License', value: 'Commercial / Extended' },
      { label: 'Last Updated', value: 'Oct 24, 2024' },
      { label: 'OS Compatibility', value: 'Windows, Linux, macOS' },
    ],
    reviews: [
      { id: 'r1', author: 'Alex R.', rating: 5, content: 'Best automation toolkit I\'ve ever purchased. The documentation is top-notch and saved me weeks of development time.', date: '2024-10-15' },
      { id: 'r2', author: 'Sarah L.', rating: 5, content: 'Excellent support team. Had a minor issue with the scraper config and they responded within an hour with a fix.', date: '2024-10-10' },
    ],
  },
  {
    id: '10',
    name: 'Node.js Web Scraper',
    slug: 'nodejs-web-scraper',
    description: 'Professional web scraping tool',
    price: 75,
    rating: 4,
    reviewCount: 87,
    category: 'Web Scrapers',
    icon: 'database',
    iconColor: 'blue',
    tags: ['JavaScript', 'Node.js'],
    badge: 'NEW',
    images: [
      { url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvO_4p2ZHk3KJpXIKRaPxhahZ8fC5c6Ep1ii4Ag9NPHSF4u8B6OJBKlF0EMkQW3Il7TPAKtOrqdr0OlIVWLuq5SuDvgsoVcsfWCJymRcNoBb8oUE9000jHw7R-B3x4w0SNKIw13OTBsqdGlmczJdoxZG_UEcPQpD3LrcXm18n_8OeNvRRLso7wqgvc9ALsjpM_MKRWmbsgLQZZtV38rJHQ1o5PF5WkGoxK71hhBJwZEEViuOP3LTPKt6BjJrwTTY2GFme74AvcnfYK', isPrimary: true },
    ],
  },
  {
    id: '11',
    name: 'PHP SaaS Starter Kit',
    slug: 'php-saas-starter-kit',
    description: 'Launch your SaaS quickly',
    price: 199,
    rating: 5,
    reviewCount: 156,
    category: 'SaaS Kits',
    icon: 'rocket',
    iconColor: 'primary',
    tags: ['PHP', 'SaaS'],
    badge: 'HOT',
    images: [
      { url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgnvTGP1cP71-2K42X4efzz9kituVYklUs7w-ZhyKCbYnU3eighsa2i88vw0J7yhNf1NBWRnCxYAN90-C-c8cJEmxGhqsgcp57fQ5syfMgHb7lyPKHQBHcMmSsmd1TKWX1n2Q4FFZsq5nLcd1C4qA4xLR_PYCKi-F_F8n0R1wb9Yg0ezrfScE22pNHnQYUUbpg_Xl5S9tV1yjqXM_dANi_UGAWqxVZUvGfD9h0BFZuqPvF2ggFFh4Y4eKicS2t5hQHiPbRAwF1Mc2t', isPrimary: true },
    ],
  },
  {
    id: '12',
    name: 'React Admin Dashboard',
    slug: 'react-admin-dashboard',
    description: 'Modern admin panel',
    price: 89,
    priceRange: { min: 89, max: 150 },
    rating: 5,
    reviewCount: 203,
    category: 'Dashboards',
    icon: 'dashboard',
    iconColor: 'purple',
    tags: ['React', 'Admin'],
    images: [
      { url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvV-45RyTmbKIQCa36fzlSVMVYb5gGDkCXidCEpOmFudHXYXPTzYiQWc0YZ-OTc1tSbc3fPYE4Gklt7239PKNccWU96xOg79Q5KHk_qjX8aXbW0v7aMmkt19JjuYOapQuJqA6uzIXtnPMJowe4HL5gpMMqL7KfTUvWd4AtZslqJtfLSkq-RWlm1AMS7besbHc7CfPHQIJrXj5twksktnxm3redMcLt0sqCmfI3dIndRI19jQ2BYJ4vOg6wa8hI6xe190LhHxB9YJe3', isPrimary: true },
    ],
  },
  {
    id: '13',
    name: 'Discord Bot Framework',
    slug: 'discord-bot-framework',
    description: 'Build Discord bots easily',
    price: 35,
    rating: 4,
    reviewCount: 67,
    category: 'Automation',
    icon: 'sparkles',
    iconColor: 'pink',
    tags: ['Discord', 'Bot'],
    images: [
      { url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhIwp7z7NlvLUeIxZqu_fjCpAYA5Z6ImAVVvS5uflJUOIgnivho1DhmCU3db76q8OgTtRribki8NKicoJBg_bVLvjBdBgpzGxkKW5RyVGTFn2rFGfSDX8Uuj3Nt2xl7cm5xamD6nbGUFOUAKEtQ-_bc4S32fQjwikQVRo8JxChuq9KU_YyYbNDn33FV-XC7eLr7yLxKDYtzy--deptYSQRHbPFCdjsvkevrroLDqgjMpFWIr1-z8e6HoLtKzXK7obMNCeGAqWoCzfB', isPrimary: true },
    ],
  },
  {
    id: '14',
    name: 'Crypto Trading Engine',
    slug: 'crypto-trading-engine',
    description: 'Algorithmic trading system',
    price: 499,
    priceRange: { min: 499, max: 850 },
    rating: 5,
    reviewCount: 45,
    category: 'Crypto/Web3',
    icon: 'bitcoin',
    iconColor: 'cyan',
    tags: ['Crypto', 'Trading'],
    badge: 'HOT',
    images: [
      { url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgnvTGP1cP71-2K42X4efzz9kituVYklUs7w-ZhyKCbYnU3eighsa2i88vw0J7yhNf1NBWRnCxYAN90-C-c8cJEmxGhqsgcp57fQ5syfMgHb7lyPKHQBHcMmSsmd1TKWX1n2Q4FFZsq5nLcd1C4qA4xLR_PYCKi-F_F8n0R1wb9Yg0ezrfScE22pNHnQYUbpg_Xl5S9tV1yjqXM_dANi_UGAWqxVZUvGfD9h0BFZuqPvF2ggFFh4Y4eKicS2t5hQHiPbRAwF1Mc2t', isPrimary: true },
    ],
  },
]

export const scriptCategories: Category[] = [
  { id: 'c1', name: 'Web Development', icon: 'code', href: '/scripts' },
  { id: 'c2', name: 'Data Science', icon: 'chart', href: '/scripts' },
  { id: 'c3', name: 'Machine Learning', icon: 'sparkles', href: '/scripts' },
  { id: 'c4', name: 'Blockchain', icon: 'bitcoin', href: '/scripts' },
]


export const relatedProducts: Product[] = [
  {
    id: 'rel1',
    name: 'Data Scraper Pro',
    slug: 'data-scraper-pro',
    description: 'Advanced web scraping',
    price: 29,
    rating: 4.8,
    reviewCount: 67,
    category: 'Web Scraping',
    icon: 'globe',
    iconColor: 'primary',
    tags: ['Scraping'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvO_4p2ZHk3KJpXIKRaPxhahZ8fC5c6Ep1ii4Ag9NPHSF4u8B6OJBKlF0EMkQW3Il7TPAKtOrqdr0OlIVWLuq5SuDvgsoVcsfWCJymRcNoBb8oUE9000jHw7R-B3x4w0SNKIw13OTBsqdGlmczJdoxZG_UEcPQpD3LrcXm18n_8OeNvRRLso7wqgvc9ALsjpM_MKRWmbsgLQZZtV38rJHQ1o5PF5WkGoxK71hhBJwZEEViuOP3LTPKt6BjJrwTTY2GFme74AvcnfYK',
  },
  {
    id: 'rel2',
    name: 'API Shield Connect',
    slug: 'api-shield-connect',
    description: 'Secure API gateway',
    price: 59,
    rating: 4.9,
    reviewCount: 89,
    category: 'Security',
    icon: 'shield',
    iconColor: 'primary',
    tags: ['Security'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgnvTGP1cP71-2K42X4efzz9kituVYklUs7w-ZhyKCbYnU3eighsa2i88vw0J7yhNf1NBWRnCxYAN90-C-c8cJEmxGhqsgcp57fQ5syfMgHb7lyPKHQBHcMmSsmd1TKWX1n2Q4FFZsq5nLcd1C4qA4xLR_PYCKi-F_F8n0R1wb9Yg0ezrfScE22pNHnQYUUbpg_Xl5S9tV1yjqXM_dANi_UGAWqxVZUvGfD9h0BFZuqPvF2ggFFh4Y4eKicS2t5hQHiPbRAwF1Mc2t',
  },
  {
    id: 'rel3',
    name: 'CloudSync Utility',
    slug: 'cloudsync-utility',
    description: 'Cloud file sync tool',
    price: 35,
    rating: 4.7,
    reviewCount: 45,
    category: 'Cloud',
    icon: 'cloud',
    iconColor: 'primary',
    tags: ['Cloud'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvV-45RyTmbKIQCa36fzlSVMVYb5gGDkCXidCEpOmFudHXYXPTzYiQWc0YZ-OTc1tSbc3fPYE4Gklt7239PKNccWU96xOg79Q5KHk_qjX8aXbW0v7aMmkt19JjuYOapQuJqA6uzIXtnPMJowe4HL5gpMMqL7KfTUvWd4AtZslqJtfLSkq-RWlm1AMS7besbHc7CfPHQIJrXj5twksktnxm3redMcLt0sqCmfI3dIndRI19jQ2BYJ4vOg6wa8hI6xe190LhHxB9YJe3',
  },
  {
    id: 'rel4',
    name: 'Bot Master Framework',
    slug: 'bot-master-framework',
    description: 'Bot development kit',
    price: 89,
    rating: 5.0,
    reviewCount: 123,
    category: 'Automation',
    icon: 'sparkles',
    iconColor: 'primary',
    tags: ['Automation'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhIwp7z7NlvLUeIxZqu_fjCpAYA5Z6ImAVVvS5uflJUOIgnivho1DhmCU3db76q8OgTtRribki8NKicoJBg_bVLvjBdBgpzGxkKW5RyVGTFn2rFGfSDX8Uuj3Nt2xl7cm5xamD6nbGUFOUAKEtQ-_bc4S32fQjwikQVRo8JxChuq9KU_YyYbNDn33FV-XC7eLr7yLxKDYtzy--deptYSQRHbPFCdjsvkevrroLDqgjMpFWIr1-z8e6HoLtKzXK7obMNCeGAqWoCzfB',
  },
  {
    id: 'rel5',
    name: 'Network Guardian',
    slug: 'network-guardian',
    description: 'Network monitoring tool',
    price: 42,
    rating: 4.6,
    reviewCount: 34,
    category: 'Networking',
    icon: 'wifi',
    iconColor: 'primary',
    tags: ['Networking'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgnvTGP1cP71-2K42X4efzz9kituVYklUs7w-ZhyKCbYnU3eighsa2i88vw0J7yhNf1NBWRnCxYAN90-C-c8cJEmxGhqsgcp57fQ5syfMgHb7lyPKHQBHcMmSsmd1TKWX1n2Q4FFZsq5nLcd1C4qA4xLR_PYCKi-F_F8n0R1wb9Yg0ezrfScE22pNHnQYUUbpg_Xl5S9tV1yjqXM_dANi_UGAWqxVZUvGfD9h0BFZuqPvF2ggFFh4Y4eKicS2t5hQHiPbRAwF1Mc2t',
  },
]

export const filterCategories = [
  'Automation',
  'Web Scrapers',
  'SaaS Kits',
  'Dashboards',
  'Crypto/Web3',
]

export const filterLanguages = ['Python', 'JS', 'PHP', 'React', 'Go', 'Rust']

// eSIM Mock Data
import { EsimPlan, EsimRegion, VirtualNumber, VirtualNumberCountry, GiftCard, GiftCardCategory } from './types'

export const esimRegions: EsimRegion[] = [
  { id: 'global', name: 'Global', flag: '🌍', planCount: 12, startingPrice: 19 },
  { id: 'north-america', name: 'North America', flag: '🇺🇸', planCount: 8, startingPrice: 15 },
  { id: 'europe', name: 'Europe', flag: '🇪🇺', planCount: 15, startingPrice: 12 },
  { id: 'asia', name: 'Asia Pacific', flag: '🌏', planCount: 18, startingPrice: 10 },
  { id: 'middle-east', name: 'Middle East', flag: '🇦🇪', planCount: 6, startingPrice: 18 },
  { id: 'africa', name: 'Africa', flag: '🌍', planCount: 8, startingPrice: 20 },
]

export const esimPlans: EsimPlan[] = [
  {
    id: 'global-1gb',
    name: 'Global Starter',
    region: 'Global',
    countries: ['100+ countries'],
    data: '1GB',
    validity: '7 days',
    price: 19,
    features: ['Instant activation', '4G/LTE speeds', '24/7 support'],
  },
  {
    id: 'global-5gb',
    name: 'Global Explorer',
    region: 'Global',
    countries: ['100+ countries'],
    data: '5GB',
    validity: '30 days',
    price: 39,
    originalPrice: 49,
    popular: true,
    features: ['Instant activation', '4G/LTE speeds', '24/7 support', 'Data rollover'],
  },
  {
    id: 'global-10gb',
    name: 'Global Pro',
    region: 'Global',
    countries: ['100+ countries'],
    data: '10GB',
    validity: '30 days',
    price: 69,
    features: ['Instant activation', '5G ready', '24/7 priority support', 'Data rollover'],
  },
  {
    id: 'usa-3gb',
    name: 'USA Essential',
    region: 'North America',
    countries: ['United States'],
    data: '3GB',
    validity: '15 days',
    price: 15,
    features: ['Instant activation', '4G/LTE speeds', 'All carriers'],
  },
  {
    id: 'usa-10gb',
    name: 'USA Power',
    region: 'North America',
    countries: ['United States', 'Canada', 'Mexico'],
    data: '10GB',
    validity: '30 days',
    price: 35,
    popular: true,
    features: ['Instant activation', '5G ready', 'Unlimited calls', 'Data sharing'],
  },
  {
    id: 'europe-5gb',
    name: 'Europe Explorer',
    region: 'Europe',
    countries: ['40+ European countries'],
    data: '5GB',
    validity: '30 days',
    price: 25,
    popular: true,
    features: ['Instant activation', '4G/LTE speeds', 'EU roaming included'],
  },
  {
    id: 'europe-unlimited',
    name: 'Europe Unlimited',
    region: 'Europe',
    countries: ['40+ European countries'],
    data: 'Unlimited',
    validity: '30 days',
    price: 59,
    features: ['Instant activation', '5G ready', 'Unlimited data', 'Speed boost'],
  },
  {
    id: 'asia-5gb',
    name: 'Asia Traveler',
    region: 'Asia Pacific',
    countries: ['Japan', 'South Korea', 'Thailand', 'Singapore', '+15 more'],
    data: '5GB',
    validity: '15 days',
    price: 22,
    features: ['Instant activation', '4G/LTE speeds', 'Multi-country'],
  },
]

// Virtual Numbers Mock Data
export const virtualNumberCountries: VirtualNumberCountry[] = [
  { id: 'us', name: 'United States', flag: '🇺🇸', code: '+1', numberCount: 50, startingPrice: 5 },
  { id: 'uk', name: 'United Kingdom', flag: '🇬🇧', code: '+44', numberCount: 35, startingPrice: 6 },
  { id: 'ca', name: 'Canada', flag: '🇨🇦', code: '+1', numberCount: 25, startingPrice: 5 },
  { id: 'de', name: 'Germany', flag: '🇩🇪', code: '+49', numberCount: 20, startingPrice: 7 },
  { id: 'fr', name: 'France', flag: '🇫🇷', code: '+33', numberCount: 18, startingPrice: 7 },
  { id: 'au', name: 'Australia', flag: '🇦🇺', code: '+61', numberCount: 15, startingPrice: 8 },
  { id: 'jp', name: 'Japan', flag: '🇯🇵', code: '+81', numberCount: 12, startingPrice: 10 },
  { id: 'sg', name: 'Singapore', flag: '🇸🇬', code: '+65', numberCount: 10, startingPrice: 9 },
]

export const virtualNumbers: VirtualNumber[] = [
  {
    id: 'us-local-1',
    country: 'United States',
    countryCode: '+1',
    flag: '🇺🇸',
    areaCode: '212',
    type: 'local',
    price: 5,
    setupFee: 0,
    features: ['SMS & Voice', 'Call forwarding', 'Voicemail', 'API access'],
    available: true,
  },
  {
    id: 'us-local-2',
    country: 'United States',
    countryCode: '+1',
    flag: '🇺🇸',
    areaCode: '415',
    type: 'local',
    price: 5,
    setupFee: 0,
    features: ['SMS & Voice', 'Call forwarding', 'Voicemail', 'API access'],
    available: true,
  },
  {
    id: 'us-tollfree',
    country: 'United States',
    countryCode: '+1',
    flag: '🇺🇸',
    areaCode: '800',
    type: 'toll-free',
    price: 15,
    setupFee: 10,
    features: ['Toll-free calls', 'Call forwarding', 'IVR support', 'Analytics'],
    available: true,
  },
  {
    id: 'uk-local-1',
    country: 'United Kingdom',
    countryCode: '+44',
    flag: '🇬🇧',
    areaCode: '20',
    type: 'local',
    price: 6,
    setupFee: 0,
    features: ['SMS & Voice', 'Call forwarding', 'Voicemail', 'API access'],
    available: true,
  },
  {
    id: 'uk-mobile',
    country: 'United Kingdom',
    countryCode: '+44',
    flag: '🇬🇧',
    areaCode: '7',
    type: 'mobile',
    price: 8,
    setupFee: 5,
    features: ['SMS & Voice', 'WhatsApp ready', 'Call forwarding', 'API access'],
    available: true,
  },
  {
    id: 'ca-local-1',
    country: 'Canada',
    countryCode: '+1',
    flag: '🇨🇦',
    areaCode: '416',
    type: 'local',
    price: 5,
    setupFee: 0,
    features: ['SMS & Voice', 'Call forwarding', 'Voicemail', 'API access'],
    available: true,
  },
  {
    id: 'de-local-1',
    country: 'Germany',
    countryCode: '+49',
    flag: '🇩🇪',
    areaCode: '30',
    type: 'local',
    price: 7,
    setupFee: 0,
    features: ['Voice only', 'Call forwarding', 'Voicemail', 'API access'],
    available: true,
  },
  {
    id: 'jp-local-1',
    country: 'Japan',
    countryCode: '+81',
    flag: '🇯🇵',
    areaCode: '3',
    type: 'local',
    price: 10,
    setupFee: 5,
    features: ['Voice only', 'Call forwarding', 'Voicemail'],
    available: false,
  },
]

// Gift Cards Mock Data
export const giftCardCategories: GiftCardCategory[] = [
  { id: 'gaming', name: 'Gaming', icon: 'sparkles', cardCount: 25 },
  { id: 'shopping', name: 'Shopping', icon: 'shopping-bag', cardCount: 30 },
  { id: 'entertainment', name: 'Entertainment', icon: 'play', cardCount: 18 },
  { id: 'food', name: 'Food & Dining', icon: 'store', cardCount: 15 },
  { id: 'travel', name: 'Travel', icon: 'airplane', cardCount: 12 },
  { id: 'crypto', name: 'Crypto', icon: 'bitcoin', cardCount: 8 },
]

export const giftCards: GiftCard[] = [
  {
    id: 'steam',
    brand: 'Steam',
    category: 'gaming',
    denominations: [10, 25, 50, 100],
    discount: 5,
    image: '/images/gift-cards/steam.png',
    popular: true,
    description: 'Perfect for PC gamers. Use on Steam for games, DLC, and more.',
  },
  {
    id: 'playstation',
    brand: 'PlayStation Store',
    category: 'gaming',
    denominations: [10, 25, 50, 100],
    discount: 3,
    image: '/images/gift-cards/playstation.png',
    popular: true,
    description: 'For PS4/PS5 games, add-ons, movies, and PS Plus.',
  },
  {
    id: 'xbox',
    brand: 'Xbox',
    category: 'gaming',
    denominations: [10, 25, 50, 100],
    discount: 3,
    image: '/images/gift-cards/xbox.png',
    description: 'For Xbox games, Game Pass, movies, and apps.',
  },
  {
    id: 'nintendo',
    brand: 'Nintendo eShop',
    category: 'gaming',
    denominations: [10, 20, 35, 50],
    discount: 2,
    image: '/images/gift-cards/nintendo.png',
    description: 'For Nintendo Switch games and Nintendo Online.',
  },
  {
    id: 'amazon',
    brand: 'Amazon',
    category: 'shopping',
    denominations: [25, 50, 100, 200],
    discount: 4,
    image: '/images/gift-cards/amazon.png',
    popular: true,
    description: 'Shop millions of items on Amazon.',
  },
  {
    id: 'ebay',
    brand: 'eBay',
    category: 'shopping',
    denominations: [25, 50, 100],
    discount: 3,
    image: '/images/gift-cards/ebay.png',
    description: 'Shop for anything on eBay.',
  },
  {
    id: 'netflix',
    brand: 'Netflix',
    category: 'entertainment',
    denominations: [15, 30, 60, 100],
    discount: 5,
    image: '/images/gift-cards/netflix.png',
    popular: true,
    description: 'Stream movies, TV shows, and more.',
  },
  {
    id: 'spotify',
    brand: 'Spotify',
    category: 'entertainment',
    denominations: [10, 30, 60],
    discount: 4,
    image: '/images/gift-cards/spotify.png',
    description: 'Listen to millions of songs ad-free.',
  },
  {
    id: 'apple',
    brand: 'Apple / iTunes',
    category: 'entertainment',
    denominations: [15, 25, 50, 100],
    discount: 3,
    image: '/images/gift-cards/apple.png',
    description: 'For App Store, Apple Music, iCloud, and more.',
  },
  {
    id: 'google-play',
    brand: 'Google Play',
    category: 'entertainment',
    denominations: [10, 25, 50, 100],
    discount: 3,
    image: '/images/gift-cards/google-play.png',
    description: 'For apps, games, movies, books, and more.',
  },
  {
    id: 'uber',
    brand: 'Uber',
    category: 'travel',
    denominations: [25, 50, 100],
    discount: 5,
    image: '/images/gift-cards/uber.png',
    description: 'For Uber rides and Uber Eats.',
  },
  {
    id: 'airbnb',
    brand: 'Airbnb',
    category: 'travel',
    denominations: [50, 100, 200],
    discount: 4,
    image: '/images/gift-cards/airbnb.png',
    description: 'Book unique accommodations worldwide.',
  },
  {
    id: 'doordash',
    brand: 'DoorDash',
    category: 'food',
    denominations: [15, 25, 50],
    discount: 5,
    image: '/images/gift-cards/doordash.png',
    description: 'Order food delivery from local restaurants.',
  },
  {
    id: 'starbucks',
    brand: 'Starbucks',
    category: 'food',
    denominations: [10, 25, 50],
    discount: 3,
    image: '/images/gift-cards/starbucks.png',
    description: 'Get your favorite coffee and treats.',
  },
  {
    id: 'bitcoin-voucher',
    brand: 'Bitcoin Voucher',
    category: 'crypto',
    denominations: [25, 50, 100, 250],
    discount: 2,
    image: '/images/gift-cards/bitcoin.png',
    popular: true,
    description: 'Redeem for Bitcoin instantly.',
  },
]
