import { Product, Category, ConnectivityOption, NavItem } from './types'

export const navCategories: NavItem[] = [
  { label: 'Scripts', href: '/products?category=scripts' },
  { label: 'eSIMs', href: '/products?category=esims' },
  { label: 'Virtual Numbers', href: '/products?category=virtual-numbers' },
  { label: 'Gift Cards', href: '/products?category=gift-cards' },
  { label: 'API Access', href: '/products?category=api' },
  { label: 'Tools', href: '/products?category=tools' },
  { label: 'Bundles', href: '/products?category=bundles' },
]

export const recommendedProducts: Product[] = [
  {
    id: '1',
    name: 'Python Automation Script',
    slug: 'python-automation-script',
    description: 'Automate your workflow with Python',
    price: 80,
    rating: 5,
    reviewCount: 124,
    category: 'Scripts',
    icon: 'terminal',
    iconColor: 'yellow',
    tags: ['Python', 'Automation'],
    badge: 'KSU',
  },
  {
    id: '2',
    name: 'Global eSIM (10GB)',
    slug: 'global-esim-10gb',
    description: 'Stay connected worldwide',
    price: 25,
    rating: 5,
    reviewCount: 89,
    category: 'eSIMs',
    icon: 'public',
    iconColor: 'green',
    tags: ['eSIM', 'Global'],
    badge: 'HOT',
  },
  {
    id: '3',
    name: 'Cloud Database Helper',
    slug: 'cloud-database-helper',
    description: 'Manage your cloud databases',
    price: 45,
    rating: 5,
    reviewCount: 56,
    category: 'Tools',
    icon: 'database',
    iconColor: 'blue',
    tags: ['Database', 'Cloud'],
    badge: 'KSU',
  },
  {
    id: '4',
    name: 'AI Analysis Suite',
    slug: 'ai-analysis-suite',
    description: 'AI-powered analytics tools',
    price: 120,
    rating: 5,
    reviewCount: 34,
    category: 'Tools',
    icon: 'psychology',
    iconColor: 'purple',
    tags: ['AI', 'Analytics'],
    badge: 'NEW',
  },
]

export const popularProducts: Product[] = [
  {
    id: '5',
    name: 'Automated Trading Bot',
    slug: 'automated-trading-bot',
    description: 'Automated crypto trading',
    price: 100,
    priceRange: { min: 100, max: 500 },
    rating: 5,
    reviewCount: 234,
    category: 'Scripts',
    icon: 'insights',
    iconColor: 'orange',
    tags: ['Trading', 'Crypto'],
  },
  {
    id: '6',
    name: 'European eSIM Pro',
    slug: 'european-esim-pro',
    description: 'European coverage eSIM',
    price: 25,
    priceRange: { min: 25, max: 45 },
    rating: 5,
    reviewCount: 189,
    category: 'eSIMs',
    icon: 'language',
    iconColor: 'green',
    tags: ['eSIM', 'Europe'],
  },
  {
    id: '7',
    name: 'Private VIP Numbers',
    slug: 'private-vip-numbers',
    description: 'Premium virtual numbers',
    price: 15,
    priceRange: { min: 15, max: 30 },
    rating: 5,
    reviewCount: 156,
    category: 'Virtual Numbers',
    icon: 'settings_input_antenna',
    iconColor: 'indigo',
    tags: ['Numbers', 'VIP'],
  },
  {
    id: '8',
    name: 'SEO Optimization Tool',
    slug: 'seo-optimization-tool',
    description: 'Boost your SEO rankings',
    price: 40,
    priceRange: { min: 40, max: 120 },
    rating: 5,
    reviewCount: 98,
    category: 'Tools',
    icon: 'lightbulb',
    iconColor: 'primary',
    tags: ['SEO', 'Marketing'],
  },
]

export const scriptProducts: Product[] = [
  {
    id: '9',
    name: 'Python Automation Suite',
    slug: 'python-automation-suite',
    description: 'Complete automation toolkit',
    price: 49,
    priceRange: { min: 49, max: 120 },
    rating: 5,
    reviewCount: 124,
    category: 'Automation',
    icon: 'terminal',
    iconColor: 'orange',
    tags: ['Python'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvwgfYMEvcI_nX3811VEyCy34SMnKHy9dmdnqG3nSMOUjjKLHrwM1Buu7vIN4sHUv_IHj3lxtx8AuvVgtQJrjdBjilef-qD6NbH3AMwpj-xP3Cl3XD4r8kxRx3ZJzJe8Y-Z4MqVrZdrhg60-dWHm_iNTlUzZhPqmEvucOUsNN2Cqq1nlRE-lUiK6PR4GpN2-YM32iXvk86ERNf_KfTr8v3fkU0u395JRo_hw-hlhfenuygiypi5Pyn0V13zGizBFBqXGrkP8TTlHSx',
    seller: {
      id: 's1',
      name: 'DevStudio Pro',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGUCLNWcUo0J-ozj8dZhQWGNJOY4ZTHR9607k1ISKsm9ponmbT6D1HqmngWq_ba6QcYc4gUb27RXhWseOvh2s76qiCa30rOvZSm6Y0WiLIj6F-Hc5idHj4aKadRxrDH5qUlIWq5P08AbAyu2b5oUiYY7odzt8AnYIcFkip_65tGErCzVJjRd_tF26tNDlL2JFVY65qGxch9uZpjjllyEkce4irYdD84-kAlxNCc4dgtWuY0nLVsUEjQZRm8loC14Dv96iyGK-WsH4M',
      verified: true,
      badge: 'Top Seller',
    },
    features: [
      { icon: 'speed', title: 'High Performance', description: 'Asynchronous I/O processing for maximum efficiency and speed.' },
      { icon: 'shield', title: 'Secure by Design', description: 'Built-in encryption, credential management, and security protocols.' },
      { icon: 'settings_suggest', title: 'Easy Configuration', description: 'Simple YAML-based configuration for quick setup and deployment.' },
      { icon: 'cloud_sync', title: 'Cloud Ready', description: 'Seamless integration with AWS, Google Cloud, and Azure services.' },
    ],
    specs: [
      { label: 'Language', value: 'Python 3.10+' },
      { label: 'Dependencies', value: 'Pandas, Scrapy, Selenium, PyYAML' },
      { label: 'License', value: 'Commercial / Extended' },
      { label: 'Last Updated', value: 'Oct 24, 2024' },
      { label: 'OS Compatibility', value: 'Windows, Linux, macOS' },
    ],
    reviews: [
      { id: 'r1', author: 'Alex R.', rating: 5, content: 'Best automation toolkit I\'ve ever purchased. The documentation is top-notch and saved me weeks of development time.', date: '2024-10-15' },
      { id: 'r2', author: 'Sarah L.', rating: 5, content: 'Excellent support team. Had a minor issue with the scraper config and they responded within an hour with a fix.', date: '2024-10-10' },
    ],
  },
  {
    id: '10',
    name: 'Node.js Web Scraper',
    slug: 'nodejs-web-scraper',
    description: 'Professional web scraping tool',
    price: 75,
    rating: 4,
    reviewCount: 87,
    category: 'Web Scrapers',
    icon: 'dataset',
    iconColor: 'blue',
    tags: ['JavaScript', 'Node.js'],
  },
  {
    id: '11',
    name: 'PHP SaaS Starter Kit',
    slug: 'php-saas-starter-kit',
    description: 'Launch your SaaS quickly',
    price: 199,
    rating: 5,
    reviewCount: 156,
    category: 'SaaS Kits',
    icon: 'rocket_launch',
    iconColor: 'primary',
    tags: ['PHP', 'SaaS'],
  },
  {
    id: '12',
    name: 'React Admin Dashboard',
    slug: 'react-admin-dashboard',
    description: 'Modern admin panel',
    price: 89,
    priceRange: { min: 89, max: 150 },
    rating: 5,
    reviewCount: 203,
    category: 'Dashboards',
    icon: 'dashboard',
    iconColor: 'purple',
    tags: ['React', 'Admin'],
  },
  {
    id: '13',
    name: 'Discord Bot Framework',
    slug: 'discord-bot-framework',
    description: 'Build Discord bots easily',
    price: 35,
    rating: 4,
    reviewCount: 67,
    category: 'Automation',
    icon: 'smart_toy',
    iconColor: 'pink',
    tags: ['Discord', 'Bot'],
  },
  {
    id: '14',
    name: 'Crypto Trading Engine',
    slug: 'crypto-trading-engine',
    description: 'Algorithmic trading system',
    price: 499,
    priceRange: { min: 499, max: 850 },
    rating: 5,
    reviewCount: 45,
    category: 'Crypto/Web3',
    icon: 'currency_bitcoin',
    iconColor: 'cyan',
    tags: ['Crypto', 'Trading'],
  },
]

export const scriptCategories: Category[] = [
  { id: 'c1', name: 'Web Development', icon: 'code', href: '/products?category=web-development' },
  { id: 'c2', name: 'Data Science', icon: 'science', href: '/products?category=data-science' },
  { id: 'c3', name: 'Machine Learning', icon: 'memory', href: '/products?category=machine-learning' },
  { id: 'c4', name: 'Blockchain', icon: 'token', href: '/products?category=blockchain' },
]

export const connectivityOptions: ConnectivityOption[] = [
  { id: 'conn1', name: 'Global Roaming eSIM', icon: 'sim_card', href: '/products?category=esims&type=global' },
  { id: 'conn2', name: 'North America eSIM', icon: 'map', href: '/products?category=esims&type=north-america' },
  { id: 'conn3', name: 'Europe eSIM', icon: 'explore', href: '/products?category=esims&type=europe' },
  { id: 'conn4', name: 'Asia eSIM', icon: 'public', href: '/products?category=esims&type=asia' },
  { id: 'conn5', name: 'USA Virtual Number', icon: 'call', href: '/products?category=virtual-numbers&country=usa' },
  { id: 'conn6', name: 'UK Virtual Number', icon: 'call', href: '/products?category=virtual-numbers&country=uk' },
  { id: 'conn7', name: 'Canada Virtual Number', icon: 'call', href: '/products?category=virtual-numbers&country=canada' },
  { id: 'conn8', name: 'Toll-Free Numbers', icon: 'tty', href: '/products?category=virtual-numbers&type=toll-free' },
]

export const relatedProducts: Product[] = [
  {
    id: 'rel1',
    name: 'Data Scraper Pro',
    slug: 'data-scraper-pro',
    description: 'Advanced web scraping',
    price: 29,
    rating: 4.8,
    reviewCount: 67,
    category: 'Web Scraping',
    icon: 'language',
    iconColor: 'primary',
    tags: ['Scraping'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvO_4p2ZHk3KJpXIKRaPxhahZ8fC5c6Ep1ii4Ag9NPHSF4u8B6OJBKlF0EMkQW3Il7TPAKtOrqdr0OlIVWLuq5SuDvgsoVcsfWCJymRcNoBb8oUE9000jHw7R-B3x4w0SNKIw13OTBsqdGlmczJdoxZG_UEcPQpD3LrcXm18n_8OeNvRRLso7wqgvc9ALsjpM_MKRWmbsgLQZZtV38rJHQ1o5PF5WkGoxK71hhBJwZEEViuOP3LTPKt6BjJrwTTY2GFme74AvcnfYK',
  },
  {
    id: 'rel2',
    name: 'API Shield Connect',
    slug: 'api-shield-connect',
    description: 'Secure API gateway',
    price: 59,
    rating: 4.9,
    reviewCount: 89,
    category: 'Security',
    icon: 'shield',
    iconColor: 'primary',
    tags: ['Security'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgnvTGP1cP71-2K42X4efzz9kituVYklUs7w-ZhyKCbYnU3eighsa2i88vw0J7yhNf1NBWRnCxYAN90-C-c8cJEmxGhqsgcp57fQ5syfMgHb7lyPKHQBHcMmSsmd1TKWX1n2Q4FFZsq5nLcd1C4qA4xLR_PYCKi-F_F8n0R1wb9Yg0ezrfScE22pNHnQYUUbpg_Xl5S9tV1yjqXM_dANi_UGAWqxVZUvGfD9h0BFZuqPvF2ggFFh4Y4eKicS2t5hQHiPbRAwF1Mc2t',
  },
  {
    id: 'rel3',
    name: 'CloudSync Utility',
    slug: 'cloudsync-utility',
    description: 'Cloud file sync tool',
    price: 35,
    rating: 4.7,
    reviewCount: 45,
    category: 'Cloud',
    icon: 'cloud',
    iconColor: 'primary',
    tags: ['Cloud'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvV-45RyTmbKIQCa36fzlSVMVYb5gGDkCXidCEpOmFudHXYXPTzYiQWc0YZ-OTc1tSbc3fPYE4Gklt7239PKNccWU96xOg79Q5KHk_qjX8aXbW0v7aMmkt19JjuYOapQuJqA6uzIXtnPMJowe4HL5gpMMqL7KfTUvWd4AtZslqJtfLSkq-RWlm1AMS7besbHc7CfPHQIJrXj5twksktnxm3redMcLt0sqCmfI3dIndRI19jQ2BYJ4vOg6wa8hI6xe190LhHxB9YJe3',
  },
  {
    id: 'rel4',
    name: 'Bot Master Framework',
    slug: 'bot-master-framework',
    description: 'Bot development kit',
    price: 89,
    rating: 5.0,
    reviewCount: 123,
    category: 'Automation',
    icon: 'smart_toy',
    iconColor: 'primary',
    tags: ['Automation'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhIwp7z7NlvLUeIxZqu_fjCpAYA5Z6ImAVVvS5uflJUOIgnivho1DhmCU3db76q8OgTtRribki8NKicoJBg_bVLvjBdBgpzGxkKW5RyVGTFn2rFGfSDX8Uuj3Nt2xl7cm5xamD6nbGUFOUAKEtQ-_bc4S32fQjwikQVRo8JxChuq9KU_YyYbNDn33FV-XC7eLr7yLxKDYtzy--deptYSQRHbPFCdjsvkevrroLDqgjMpFWIr1-z8e6HoLtKzXK7obMNCeGAqWoCzfB',
  },
  {
    id: 'rel5',
    name: 'Network Guardian',
    slug: 'network-guardian',
    description: 'Network monitoring tool',
    price: 42,
    rating: 4.6,
    reviewCount: 34,
    category: 'Networking',
    icon: 'router',
    iconColor: 'primary',
    tags: ['Networking'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgnvTGP1cP71-2K42X4efzz9kituVYklUs7w-ZhyKCbYnU3eighsa2i88vw0J7yhNf1NBWRnCxYAN90-C-c8cJEmxGhqsgcp57fQ5syfMgHb7lyPKHQBHcMmSsmd1TKWX1n2Q4FFZsq5nLcd1C4qA4xLR_PYCKi-F_F8n0R1wb9Yg0ezrfScE22pNHnQYUUbpg_Xl5S9tV1yjqXM_dANi_UGAWqxVZUvGfD9h0BFZuqPvF2ggFFh4Y4eKicS2t5hQHiPbRAwF1Mc2t',
  },
]

export const filterCategories = [
  'Automation',
  'Web Scrapers',
  'SaaS Kits',
  'Dashboards',
  'Crypto/Web3',
]

export const filterLanguages = ['Python', 'JS', 'PHP', 'React', 'Go', 'Rust']
