// Static component templates for the CMS page builder
// These define the available section types, their schemas (for auto-generating property forms), and default props

import { ComponentTemplate } from './api'

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  // ─── Navigation ──────────────────────────────────────────────────
  {
    id: 'tpl-header',
    name: 'header',
    category: 'navigation',
    description: 'Page header with logo, navigation, and actions',
    icon: 'menu',
    schema: {
      type: 'object',
      properties: {
        logoUrl: { type: 'string', title: 'Logo URL' },
        logoAlt: { type: 'string', title: 'Logo Alt Text' },
        siteName: { type: 'string', title: 'Site Name' },
        navLinks: { type: 'array', title: 'Navigation Links', items: { type: 'object', properties: { label: { type: 'string' }, href: { type: 'string' } } } },
        showSearch: { type: 'boolean', title: 'Show Search' },
        showCart: { type: 'boolean', title: 'Show Cart' },
        sticky: { type: 'boolean', title: 'Sticky Header' },
      },
    },
    defaultProps: { logoUrl: '', siteName: 'My Site', navLinks: [], showSearch: true, showCart: true, sticky: true },
    thumbnail: null,
    order: 1,
    isActive: true,
  },
  {
    id: 'tpl-footer',
    name: 'footer',
    category: 'navigation',
    description: 'Page footer with links, newsletter, and social icons',
    icon: 'menu',
    schema: {
      type: 'object',
      properties: {
        logoUrl: { type: 'string', title: 'Logo URL' },
        siteName: { type: 'string', title: 'Site Name' },
        description: { type: 'string', title: 'Description' },
        columns: { type: 'array', title: 'Link Columns', items: { type: 'object', properties: { title: { type: 'string' }, links: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, href: { type: 'string' } } } } } } },
        showNewsletter: { type: 'boolean', title: 'Show Newsletter' },
        copyrightText: { type: 'string', title: 'Copyright Text' },
      },
    },
    defaultProps: { logoUrl: '', siteName: 'My Site', description: '', columns: [], showNewsletter: true, copyrightText: '' },
    thumbnail: null,
    order: 2,
    isActive: true,
  },

  // ─── Layout ──────────────────────────────────────────────────────
  {
    id: 'tpl-section',
    name: 'section',
    category: 'layout',
    description: 'Container section with configurable column layout',
    icon: 'grid-view',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        layout: { type: 'string', title: 'Layout', enum: ['1', '1/2-1/2', '1/3-2/3', '2/3-1/3', '1/3-1/3-1/3', '1/4-1/4-1/4-1/4', '1/4-1/2-1/4', '1/4-3/4', '3/4-1/4'] },
        gap: { type: 'string', title: 'Gap', enum: ['none', 'small', 'medium', 'large'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        verticalAlign: { type: 'string', title: 'Vertical Align', enum: ['top', 'center', 'bottom', 'stretch'] },
      },
    },
    defaultProps: { layout: '1', gap: 'medium', padding: 'medium', maxWidth: 'container', verticalAlign: 'top' },
    thumbnail: null,
    order: 3,
    isActive: true,
  },
  {
    id: 'tpl-column',
    name: 'column',
    category: 'layout',
    description: 'Column block within a section container',
    icon: 'layers',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        text: { type: 'string', title: 'Text' },
        imageUrl: { type: 'string', title: 'Image URL' },
        buttonText: { type: 'string', title: 'Button Text' },
        buttonLink: { type: 'string', title: 'Button Link' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
      },
    },
    defaultProps: { padding: 'medium', borderRadius: 'medium', alignment: 'left' },
    thumbnail: null,
    order: 4,
    isActive: true,
  },
  {
    id: 'tpl-spacer',
    name: 'spacer',
    category: 'layout',
    description: 'Vertical spacing between sections',
    icon: 'unfold-more',
    schema: {
      type: 'object',
      properties: {
        height: { type: 'string', title: 'Height', enum: ['small', 'medium', 'large', 'xl'] },
      },
    },
    defaultProps: { height: 'medium' },
    thumbnail: null,
    order: 5,
    isActive: true,
  },
  {
    id: 'tpl-divider',
    name: 'divider',
    category: 'layout',
    description: 'Horizontal divider line',
    icon: 'remove',
    schema: {
      type: 'object',
      properties: {
        style: { type: 'string', title: 'Style', enum: ['solid', 'dashed', 'dotted'] },
        color: { type: 'string', title: 'Color' },
        width: { type: 'string', title: 'Width', enum: ['full', 'wide', 'medium', 'narrow'] },
      },
    },
    defaultProps: { style: 'solid', color: '#1f1f1f', width: 'full' },
    thumbnail: null,
    order: 6,
    isActive: true,
  },

  // ─── Marketing ─────────────────────────────────────────────────
  {
    id: 'tpl-hero',
    name: 'hero',
    category: 'marketing',
    description: 'Hero section with title, subtitle, and CTA',
    icon: 'star',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        backgroundImage: { type: 'string', title: 'Background Image URL' },
        buttonText: { type: 'string', title: 'Button Text' },
        buttonLink: { type: 'string', title: 'Button Link' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        height: { type: 'string', title: 'Height', enum: ['small', 'medium', 'large'] },
        overlayOpacity: { type: 'string', title: 'Overlay', enum: ['none', 'light', 'medium', 'dark'] },
      },
    },
    defaultProps: { title: 'Welcome', subtitle: '', alignment: 'center', height: 'large', overlayOpacity: 'medium' },
    thumbnail: null,
    order: 10,
    isActive: true,
  },
  {
    id: 'tpl-cta-banner',
    name: 'cta-banner',
    category: 'marketing',
    description: 'Call-to-action banner with gradient background',
    icon: 'campaign',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        buttonText: { type: 'string', title: 'Button Text' },
        buttonLink: { type: 'string', title: 'Button Link' },
        gradientFrom: { type: 'string', title: 'Gradient From' },
        gradientTo: { type: 'string', title: 'Gradient To' },
      },
    },
    defaultProps: { title: 'Ready to get started?', subtitle: '', buttonText: 'Get Started', buttonLink: '/', gradientFrom: '#43D678', gradientTo: '#3B82F6' },
    thumbnail: null,
    order: 11,
    isActive: true,
  },
  {
    id: 'tpl-features-grid',
    name: 'features-grid',
    category: 'marketing',
    description: 'Grid of feature cards with icons',
    icon: 'grid-view',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        features: { type: 'array', title: 'Features', items: { type: 'object', properties: { icon: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' } } } },
      },
    },
    defaultProps: { title: 'Features', columns: '3', features: [] },
    thumbnail: null,
    order: 12,
    isActive: true,
  },
  {
    id: 'tpl-testimonials',
    name: 'testimonials',
    category: 'marketing',
    description: 'Customer testimonials in a grid',
    icon: 'chat',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        layout: { type: 'string', title: 'Layout', enum: ['grid', 'carousel'] },
        testimonials: { type: 'array', title: 'Testimonials', items: { type: 'object', properties: { quote: { type: 'string' }, author: { type: 'string' }, role: { type: 'string' }, avatar: { type: 'string' } } } },
      },
    },
    defaultProps: { title: 'What our customers say', layout: 'grid', testimonials: [] },
    thumbnail: null,
    order: 13,
    isActive: true,
  },
  {
    id: 'tpl-pricing-table',
    name: 'pricing-table',
    category: 'marketing',
    description: 'Pricing comparison table',
    icon: 'payments',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        plans: { type: 'array', title: 'Plans', items: { type: 'object', properties: { name: { type: 'string' }, price: { type: 'string' }, period: { type: 'string' }, features: { type: 'array', items: { type: 'string' } }, buttonText: { type: 'string' }, buttonLink: { type: 'string' }, highlighted: { type: 'boolean' } } } },
      },
    },
    defaultProps: { title: 'Pricing', plans: [] },
    thumbnail: null,
    order: 14,
    isActive: true,
  },

  // ─── Content ──────────────────────────────────────────────────
  {
    id: 'tpl-text-block',
    name: 'text-block',
    category: 'content',
    description: 'Rich text content block',
    icon: 'note',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        content: { type: 'string', title: 'Content' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
      },
    },
    defaultProps: { title: '', content: '', alignment: 'left' },
    thumbnail: null,
    order: 20,
    isActive: true,
  },
  {
    id: 'tpl-image',
    name: 'image',
    category: 'content',
    description: 'Single image with optional caption',
    icon: 'image',
    schema: {
      type: 'object',
      properties: {
        src: { type: 'string', title: 'Image URL' },
        alt: { type: 'string', title: 'Alt Text' },
        caption: { type: 'string', title: 'Caption' },
        width: { type: 'string', title: 'Width', enum: ['full', 'large', 'medium', 'small'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
      },
    },
    defaultProps: { src: '', alt: '', width: 'full', borderRadius: 'medium' },
    thumbnail: null,
    order: 21,
    isActive: true,
  },
  {
    id: 'tpl-image-gallery',
    name: 'image-gallery',
    category: 'content',
    description: 'Multiple images in a grid',
    icon: 'photo-library',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        images: { type: 'array', title: 'Images', items: { type: 'object', properties: { src: { type: 'string' }, alt: { type: 'string' }, caption: { type: 'string' } } } },
      },
    },
    defaultProps: { columns: '3', images: [] },
    thumbnail: null,
    order: 22,
    isActive: true,
  },
  {
    id: 'tpl-video-embed',
    name: 'video-embed',
    category: 'content',
    description: 'YouTube or Vimeo video embed',
    icon: 'play-circle',
    schema: {
      type: 'object',
      properties: {
        url: { type: 'string', title: 'Video URL (YouTube/Vimeo)' },
        title: { type: 'string', title: 'Title' },
        aspectRatio: { type: 'string', title: 'Aspect Ratio', enum: ['16:9', '4:3', '1:1'] },
      },
    },
    defaultProps: { url: '', title: '', aspectRatio: '16:9' },
    thumbnail: null,
    order: 23,
    isActive: true,
  },
  {
    id: 'tpl-button-cta',
    name: 'button-cta',
    category: 'content',
    description: 'Standalone call-to-action button',
    icon: 'smart-button',
    schema: {
      type: 'object',
      properties: {
        text: { type: 'string', title: 'Button Text' },
        link: { type: 'string', title: 'Button Link' },
        variant: { type: 'string', title: 'Style', enum: ['primary', 'secondary', 'outline'] },
        size: { type: 'string', title: 'Size', enum: ['small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
      },
    },
    defaultProps: { text: 'Click Here', link: '/', variant: 'primary', size: 'medium', alignment: 'center' },
    thumbnail: null,
    order: 24,
    isActive: true,
  },
  {
    id: 'tpl-faq-accordion',
    name: 'faq-accordion',
    category: 'content',
    description: 'Expandable FAQ accordion',
    icon: 'help',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        items: { type: 'array', title: 'FAQ Items', items: { type: 'object', properties: { question: { type: 'string' }, answer: { type: 'string' } } } },
      },
    },
    defaultProps: { title: 'Frequently Asked Questions', items: [] },
    thumbnail: null,
    order: 25,
    isActive: true,
  },
  {
    id: 'tpl-custom-html',
    name: 'custom-html',
    category: 'content',
    description: 'Raw HTML/CSS code block',
    icon: 'code',
    schema: {
      type: 'object',
      properties: {
        html: { type: 'string', title: 'HTML Code' },
      },
    },
    defaultProps: { html: '' },
    thumbnail: null,
    order: 26,
    isActive: true,
  },
  {
    id: 'tpl-social-links',
    name: 'social-links',
    category: 'content',
    description: 'Social media icon links',
    icon: 'share',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        links: { type: 'array', title: 'Social Links', items: { type: 'object', properties: { platform: { type: 'string' }, url: { type: 'string' } } } },
      },
    },
    defaultProps: { title: '', alignment: 'center', links: [] },
    thumbnail: null,
    order: 27,
    isActive: true,
  },
  {
    id: 'tpl-newsletter',
    name: 'newsletter',
    category: 'content',
    description: 'Email newsletter signup form',
    icon: 'mail',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        buttonText: { type: 'string', title: 'Button Text' },
        placeholder: { type: 'string', title: 'Input Placeholder' },
      },
    },
    defaultProps: { title: 'Subscribe to our newsletter', subtitle: 'Stay updated with the latest news', buttonText: 'Subscribe', placeholder: 'Enter your email' },
    thumbnail: null,
    order: 28,
    isActive: true,
  },
  {
    id: 'tpl-stats-counter',
    name: 'stats-counter',
    category: 'content',
    description: 'Statistics counter display',
    icon: 'analytics',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        stats: { type: 'array', title: 'Stats', items: { type: 'object', properties: { number: { type: 'string' }, label: { type: 'string' }, prefix: { type: 'string' }, suffix: { type: 'string' } } } },
      },
    },
    defaultProps: { title: '', stats: [] },
    thumbnail: null,
    order: 29,
    isActive: true,
  },
  {
    id: 'tpl-map',
    name: 'map',
    category: 'content',
    description: 'Google Maps embed',
    icon: 'location-on',
    schema: {
      type: 'object',
      properties: {
        embedUrl: { type: 'string', title: 'Google Maps Embed URL' },
        height: { type: 'string', title: 'Height', enum: ['small', 'medium', 'large'] },
      },
    },
    defaultProps: { embedUrl: '', height: 'medium' },
    thumbnail: null,
    order: 30,
    isActive: true,
  },

  // ─── E-commerce ────────────────────────────────────────────────
  {
    id: 'tpl-product-showcase',
    name: 'product-showcase',
    category: 'ecommerce',
    description: 'Product grid showcase',
    icon: 'store',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        productIds: { type: 'string', title: 'Product IDs (comma-separated)' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        showPrices: { type: 'boolean', title: 'Show Prices' },
        showRatings: { type: 'boolean', title: 'Show Ratings' },
      },
    },
    defaultProps: { title: '', productIds: '', columns: '4', showPrices: true, showRatings: true },
    thumbnail: null,
    order: 40,
    isActive: true,
  },
  {
    id: 'tpl-category-grid',
    name: 'category-grid',
    category: 'ecommerce',
    description: 'Category grid with icons',
    icon: 'category',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4', '6'] },
        categories: { type: 'array', title: 'Categories', items: { type: 'object', properties: { name: { type: 'string' }, icon: { type: 'string' }, link: { type: 'string' }, count: { type: 'string' } } } },
      },
    },
    defaultProps: { title: '', columns: '4', categories: [] },
    thumbnail: null,
    order: 41,
    isActive: true,
  },
]
