// Static component templates for the CMS page builder
// These define the available section types, their schemas (for auto-generating property forms), and default props

import { ComponentTemplate } from './api'

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  // ─── Navigation ──────────────────────────────────────────────────
  {
    id: 'tpl-header',
    name: 'header',
    category: 'navigation',
    description: 'Page header with logo, navigation, and actions',
    icon: 'menu',
    schema: {
      type: 'object',
      properties: {
        logoUrl: { type: 'string', title: 'Logo URL' },
        logoAlt: { type: 'string', title: 'Logo Alt Text' },
        siteName: { type: 'string', title: 'Site Name' },
        navLinks: { type: 'array', title: 'Navigation Links', items: { type: 'object', properties: { label: { type: 'string' }, href: { type: 'string' } } } },
        showSearch: { type: 'boolean', title: 'Show Search' },
        showCart: { type: 'boolean', title: 'Show Cart' },
        sticky: { type: 'boolean', title: 'Sticky Header' },
        textColor: { type: 'string', title: 'Text Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
      },
    },
    defaultProps: { logoUrl: '', siteName: 'My Site', navLinks: [], showSearch: true, showCart: true, sticky: true },
    thumbnail: null,
    order: 1,
    isActive: true,
  },
  {
    id: 'tpl-footer',
    name: 'footer',
    category: 'navigation',
    description: 'Page footer with links, newsletter, and social icons',
    icon: 'menu',
    schema: {
      type: 'object',
      properties: {
        logoUrl: { type: 'string', title: 'Logo URL' },
        siteName: { type: 'string', title: 'Site Name' },
        description: { type: 'string', title: 'Description' },
        columns: { type: 'array', title: 'Link Columns', items: { type: 'object', properties: { title: { type: 'string' }, links: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, href: { type: 'string' } } } } } } },
        showNewsletter: { type: 'boolean', title: 'Show Newsletter' },
        copyrightText: { type: 'string', title: 'Copyright Text' },
        textColor: { type: 'string', title: 'Text Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
      },
    },
    defaultProps: { logoUrl: '', siteName: 'My Site', description: '', columns: [], showNewsletter: true, copyrightText: '' },
    thumbnail: null,
    order: 2,
    isActive: true,
  },

  // ─── Layout ──────────────────────────────────────────────────────
  {
    id: 'tpl-section',
    name: 'section',
    category: 'layout',
    description: 'Container section with configurable column layout',
    icon: 'grid-view',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        layout: { type: 'string', title: 'Layout', enum: ['1', '1/2-1/2', '1/3-2/3', '2/3-1/3', '1/3-1/3-1/3', '1/4-1/4-1/4-1/4', '1/4-1/2-1/4', '1/4-3/4', '3/4-1/4'] },
        gap: { type: 'string', title: 'Gap', enum: ['none', 'small', 'medium', 'large'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        verticalAlign: { type: 'string', title: 'Vertical Align', enum: ['top', 'center', 'bottom', 'stretch'] },
        backgroundImage: { type: 'string', title: 'Background Image' },
        overlayOpacity: { type: 'string', title: 'Overlay Opacity', enum: ['none', 'light', 'medium', 'dark'] },
        gradientFrom: { type: 'string', title: 'Gradient From' },
        gradientTo: { type: 'string', title: 'Gradient To' },
        borderWidth: { type: 'string', title: 'Border Width', enum: ['none', '1', '2', '4'] },
        borderColor: { type: 'string', title: 'Border Color' },
        borderStyle: { type: 'string', title: 'Border Style', enum: ['solid', 'dashed', 'dotted'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        paddingTop: { type: 'string', title: 'Padding Top', enum: ['none', 'small', 'medium', 'large'] },
        paddingBottom: { type: 'string', title: 'Padding Bottom', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        customId: { type: 'string', title: 'Custom ID' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
        hideOnTablet: { type: 'boolean', title: 'Hide on Tablet' },
        horizontalAlign: { type: 'string', title: 'Horizontal Align', enum: ['left', 'center', 'right'] },
      },
    },
    defaultProps: { layout: '1', gap: 'medium', padding: 'medium', maxWidth: 'container', verticalAlign: 'top' },
    thumbnail: null,
    order: 3,
    isActive: true,
  },
  {
    id: 'tpl-column',
    name: 'column',
    category: 'layout',
    description: 'Column block within a section container',
    icon: 'layers',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        text: { type: 'string', title: 'Text' },
        imageUrl: { type: 'string', title: 'Image URL' },
        buttonText: { type: 'string', title: 'Button Text' },
        buttonLink: { type: 'string', title: 'Button Link' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderWidth: { type: 'string', title: 'Border Width', enum: ['none', '1', '2', '4'] },
        borderColor: { type: 'string', title: 'Border Color' },
        borderStyle: { type: 'string', title: 'Border Style', enum: ['solid', 'dashed', 'dotted'] },
        backgroundImage: { type: 'string', title: 'Background Image' },
        overlayOpacity: { type: 'string', title: 'Overlay Opacity', enum: ['none', 'light', 'medium', 'dark'] },
        gradientFrom: { type: 'string', title: 'Gradient From' },
        gradientTo: { type: 'string', title: 'Gradient To' },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
        hideOnTablet: { type: 'boolean', title: 'Hide on Tablet' },
        verticalAlign: { type: 'string', title: 'Vertical Align', enum: ['top', 'center', 'bottom'] },
        horizontalAlign: { type: 'string', title: 'Horizontal Align', enum: ['left', 'center', 'right'] },
      },
    },
    defaultProps: { padding: 'medium', borderRadius: 'medium', alignment: 'left' },
    thumbnail: null,
    order: 4,
    isActive: true,
  },
  {
    id: 'tpl-spacer',
    name: 'spacer',
    category: 'layout',
    description: 'Vertical spacing between sections',
    icon: 'expand-more',
    schema: {
      type: 'object',
      properties: {
        height: { type: 'string', title: 'Height', enum: ['small', 'medium', 'large', 'xl'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
        hideOnTablet: { type: 'boolean', title: 'Hide on Tablet' },
      },
    },
    defaultProps: { height: 'medium' },
    thumbnail: null,
    order: 5,
    isActive: true,
  },
  {
    id: 'tpl-divider',
    name: 'divider',
    category: 'layout',
    description: 'Horizontal divider line',
    icon: 'remove',
    schema: {
      type: 'object',
      properties: {
        style: { type: 'string', title: 'Style', enum: ['solid', 'dashed', 'dotted'] },
        color: { type: 'string', title: 'Color' },
        width: { type: 'string', title: 'Width', enum: ['full', 'wide', 'medium', 'narrow'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        maxWidth: { type: 'string', title: 'Max Width' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { style: 'solid', color: '#1f1f1f', width: 'full' },
    thumbnail: null,
    order: 6,
    isActive: true,
  },

  // ─── Marketing ─────────────────────────────────────────────────
  {
    id: 'tpl-hero',
    name: 'hero',
    category: 'marketing',
    description: 'Hero section with title, subtitle, and CTA',
    icon: 'star',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        backgroundImage: { type: 'string', title: 'Background Image URL' },
        buttonText: { type: 'string', title: 'Button Text' },
        buttonLink: { type: 'string', title: 'Button Link' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        height: { type: 'string', title: 'Height', enum: ['small', 'medium', 'large'] },
        overlayOpacity: { type: 'string', title: 'Overlay', enum: ['none', 'light', 'medium', 'dark'] },
        titleColor: { type: 'string', title: 'Title Color' },
        subtitleColor: { type: 'string', title: 'Subtitle Color' },
        buttonColor: { type: 'string', title: 'Button Color' },
        buttonTextColor: { type: 'string', title: 'Button Text Color' },
        secondButtonText: { type: 'string', title: 'Second Button Text' },
        secondButtonLink: { type: 'string', title: 'Second Button Link' },
        gradientFrom: { type: 'string', title: 'Gradient From' },
        gradientTo: { type: 'string', title: 'Gradient To' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        videoUrl: { type: 'string', title: 'Video Background URL' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Welcome', subtitle: '', alignment: 'center', height: 'large', overlayOpacity: 'medium' },
    thumbnail: null,
    order: 10,
    isActive: true,
  },
  {
    id: 'tpl-cta-banner',
    name: 'cta-banner',
    category: 'marketing',
    description: 'Call-to-action banner with gradient background',
    icon: 'campaign',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        buttonText: { type: 'string', title: 'Button Text' },
        buttonLink: { type: 'string', title: 'Button Link' },
        gradientFrom: { type: 'string', title: 'Gradient From' },
        gradientTo: { type: 'string', title: 'Gradient To' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        backgroundImage: { type: 'string', title: 'Background Image' },
        titleColor: { type: 'string', title: 'Title Color' },
        subtitleColor: { type: 'string', title: 'Subtitle Color' },
        buttonColor: { type: 'string', title: 'Button Color' },
        buttonTextColor: { type: 'string', title: 'Button Text Color' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        secondButtonText: { type: 'string', title: 'Second Button Text' },
        secondButtonLink: { type: 'string', title: 'Second Button Link' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Ready to get started?', subtitle: '', buttonText: 'Get Started', buttonLink: '/', gradientFrom: '#43D678', gradientTo: '#3B82F6' },
    thumbnail: null,
    order: 11,
    isActive: true,
  },
  {
    id: 'tpl-features-grid',
    name: 'features-grid',
    category: 'marketing',
    description: 'Grid of feature cards with icons',
    icon: 'grid-view',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        features: { type: 'array', title: 'Features', items: { type: 'object', properties: { icon: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' }, imageUrl: { type: 'string' }, linkUrl: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        iconColor: { type: 'string', title: 'Icon Color' },
        cardBackgroundColor: { type: 'string', title: 'Card Background' },
        cardBorderRadius: { type: 'string', title: 'Card Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        cardBorder: { type: 'boolean', title: 'Show Card Border' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        showIcons: { type: 'boolean', title: 'Show Icons' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Features', columns: '3', features: [], showIcons: true },
    thumbnail: null,
    order: 12,
    isActive: true,
  },
  {
    id: 'tpl-testimonials',
    name: 'testimonials',
    category: 'marketing',
    description: 'Customer testimonials in a grid',
    icon: 'chat',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        layout: { type: 'string', title: 'Layout', enum: ['grid', 'carousel'] },
        testimonials: { type: 'array', title: 'Testimonials', items: { type: 'object', properties: { quote: { type: 'string' }, author: { type: 'string' }, role: { type: 'string' }, avatar: { type: 'string' }, rating: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        cardBackgroundColor: { type: 'string', title: 'Card Background' },
        textColor: { type: 'string', title: 'Text Color' },
        cardBorderRadius: { type: 'string', title: 'Card Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        showStars: { type: 'boolean', title: 'Show Star Ratings' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'What our customers say', layout: 'grid', testimonials: [], showStars: true },
    thumbnail: null,
    order: 13,
    isActive: true,
  },
  {
    id: 'tpl-pricing-table',
    name: 'pricing-table',
    category: 'marketing',
    description: 'Pricing comparison table',
    icon: 'payments',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        plans: { type: 'array', title: 'Plans', items: { type: 'object', properties: { name: { type: 'string' }, price: { type: 'string' }, period: { type: 'string' }, features: { type: 'array', items: { type: 'string' } }, buttonText: { type: 'string' }, buttonLink: { type: 'string' }, highlighted: { type: 'boolean' }, description: { type: 'string' }, badge: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        highlightColor: { type: 'string', title: 'Highlight Color' },
        cardBackgroundColor: { type: 'string', title: 'Card Background' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Pricing', plans: [], columns: '3' },
    thumbnail: null,
    order: 14,
    isActive: true,
  },

  // ─── Content ──────────────────────────────────────────────────
  {
    id: 'tpl-text-block',
    name: 'text-block',
    category: 'content',
    description: 'Rich text content block',
    icon: 'note',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        content: { type: 'string', title: 'Content' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        fontSize: { type: 'string', title: 'Font Size', enum: ['small', 'medium', 'large', 'xl'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: '', content: '', alignment: 'left' },
    thumbnail: null,
    order: 20,
    isActive: true,
  },
  {
    id: 'tpl-image',
    name: 'image',
    category: 'content',
    description: 'Single image with optional caption',
    icon: 'image',
    schema: {
      type: 'object',
      properties: {
        src: { type: 'string', title: 'Image URL' },
        alt: { type: 'string', title: 'Alt Text' },
        caption: { type: 'string', title: 'Caption' },
        width: { type: 'string', title: 'Width', enum: ['full', 'large', 'medium', 'small'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        linkUrl: { type: 'string', title: 'Link URL' },
        linkTarget: { type: 'string', title: 'Link Target', enum: ['_self', '_blank'] },
        shadow: { type: 'string', title: 'Shadow', enum: ['none', 'small', 'medium', 'large'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        objectFit: { type: 'string', title: 'Object Fit', enum: ['cover', 'contain', 'fill', 'none'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { src: '', alt: '', width: 'full', borderRadius: 'medium' },
    thumbnail: null,
    order: 21,
    isActive: true,
  },
  {
    id: 'tpl-image-gallery',
    name: 'image-gallery',
    category: 'content',
    description: 'Multiple images in a grid',
    icon: 'photo-library',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        images: { type: 'array', title: 'Images', items: { type: 'object', properties: { src: { type: 'string' }, alt: { type: 'string' }, caption: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        gap: { type: 'string', title: 'Gap', enum: ['small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Image Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        lightbox: { type: 'boolean', title: 'Enable Lightbox' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { columns: '3', images: [] },
    thumbnail: null,
    order: 22,
    isActive: true,
  },
  {
    id: 'tpl-video-embed',
    name: 'video-embed',
    category: 'content',
    description: 'YouTube or Vimeo video embed',
    icon: 'play-circle',
    schema: {
      type: 'object',
      properties: {
        url: { type: 'string', title: 'Video URL (YouTube/Vimeo)' },
        title: { type: 'string', title: 'Title' },
        aspectRatio: { type: 'string', title: 'Aspect Ratio', enum: ['16:9', '4:3', '1:1'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        autoplay: { type: 'boolean', title: 'Autoplay' },
        muted: { type: 'boolean', title: 'Muted' },
        showControls: { type: 'boolean', title: 'Show Controls' },
        caption: { type: 'string', title: 'Caption' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { url: '', title: '', aspectRatio: '16:9', showControls: true },
    thumbnail: null,
    order: 23,
    isActive: true,
  },
  {
    id: 'tpl-button-cta',
    name: 'button-cta',
    category: 'content',
    description: 'Standalone call-to-action button',
    icon: 'bolt',
    schema: {
      type: 'object',
      properties: {
        text: { type: 'string', title: 'Button Text' },
        link: { type: 'string', title: 'Button Link' },
        variant: { type: 'string', title: 'Style', enum: ['primary', 'secondary', 'outline'] },
        size: { type: 'string', title: 'Size', enum: ['small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        backgroundColor: { type: 'string', title: 'Button Color' },
        textColor: { type: 'string', title: 'Text Color' },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        borderWidth: { type: 'string', title: 'Border Width', enum: ['none', '1', '2', '4'] },
        borderColor: { type: 'string', title: 'Border Color' },
        padding: { type: 'string', title: 'Section Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        fullWidth: { type: 'boolean', title: 'Full Width' },
        icon: { type: 'string', title: 'Icon' },
        target: { type: 'string', title: 'Link Target', enum: ['_self', '_blank'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { text: 'Click Here', link: '/', variant: 'primary', size: 'medium', alignment: 'center' },
    thumbnail: null,
    order: 24,
    isActive: true,
  },
  {
    id: 'tpl-faq-accordion',
    name: 'faq-accordion',
    category: 'content',
    description: 'Expandable FAQ accordion',
    icon: 'help',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Section Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        items: { type: 'array', title: 'FAQ Items', items: { type: 'object', properties: { question: { type: 'string' }, answer: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        accentColor: { type: 'string', title: 'Accent Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        openFirst: { type: 'boolean', title: 'Open First Item' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Frequently Asked Questions', items: [] },
    thumbnail: null,
    order: 25,
    isActive: true,
  },
  {
    id: 'tpl-custom-html',
    name: 'custom-html',
    category: 'content',
    description: 'Raw HTML/CSS code block',
    icon: 'code',
    schema: {
      type: 'object',
      properties: {
        html: { type: 'string', title: 'HTML Code' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { html: '' },
    thumbnail: null,
    order: 26,
    isActive: true,
  },
  {
    id: 'tpl-social-links',
    name: 'social-links',
    category: 'content',
    description: 'Social media icon links',
    icon: 'share',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        links: { type: 'array', title: 'Social Links', items: { type: 'object', properties: { platform: { type: 'string' }, url: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        iconSize: { type: 'string', title: 'Icon Size', enum: ['small', 'medium', 'large'] },
        iconColor: { type: 'string', title: 'Icon Color' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: '', alignment: 'center', links: [] },
    thumbnail: null,
    order: 27,
    isActive: true,
  },
  {
    id: 'tpl-newsletter',
    name: 'newsletter',
    category: 'content',
    description: 'Email newsletter signup form',
    icon: 'mail',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        subtitle: { type: 'string', title: 'Subtitle' },
        buttonText: { type: 'string', title: 'Button Text' },
        placeholder: { type: 'string', title: 'Input Placeholder' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        buttonColor: { type: 'string', title: 'Button Color' },
        buttonTextColor: { type: 'string', title: 'Button Text Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        successMessage: { type: 'string', title: 'Success Message' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Subscribe to our newsletter', subtitle: 'Stay updated with the latest news', buttonText: 'Subscribe', placeholder: 'Enter your email' },
    thumbnail: null,
    order: 28,
    isActive: true,
  },
  {
    id: 'tpl-stats-counter',
    name: 'stats-counter',
    category: 'content',
    description: 'Statistics counter display',
    icon: 'analytics',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        stats: { type: 'array', title: 'Stats', items: { type: 'object', properties: { number: { type: 'string' }, label: { type: 'string' }, prefix: { type: 'string' }, suffix: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        numberColor: { type: 'string', title: 'Number Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        showDividers: { type: 'boolean', title: 'Show Dividers' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: '', stats: [], columns: '4', alignment: 'center' },
    thumbnail: null,
    order: 29,
    isActive: true,
  },
  {
    id: 'tpl-map',
    name: 'map',
    category: 'content',
    description: 'Google Maps embed',
    icon: 'location-on',
    schema: {
      type: 'object',
      properties: {
        embedUrl: { type: 'string', title: 'Google Maps Embed URL' },
        height: { type: 'string', title: 'Height', enum: ['small', 'medium', 'large'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { embedUrl: '', height: 'medium' },
    thumbnail: null,
    order: 30,
    isActive: true,
  },

  // ─── New Content Components ──────────────────────────────────
  {
    id: 'tpl-heading',
    name: 'heading',
    category: 'content',
    description: 'Standalone heading with full typography control',
    icon: 'description',
    schema: {
      type: 'object',
      properties: {
        text: { type: 'string', title: 'Text' },
        tag: { type: 'string', title: 'Tag', enum: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        color: { type: 'string', title: 'Color' },
        fontSize: { type: 'string', title: 'Font Size', enum: ['sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl'] },
        fontWeight: { type: 'string', title: 'Font Weight', enum: ['normal', 'medium', 'semibold', 'bold', 'extrabold'] },
        lineHeight: { type: 'string', title: 'Line Height', enum: ['tight', 'normal', 'relaxed'] },
        letterSpacing: { type: 'string', title: 'Letter Spacing', enum: ['tighter', 'normal', 'wide', 'wider'] },
        textTransform: { type: 'string', title: 'Text Transform', enum: ['none', 'uppercase', 'lowercase', 'capitalize'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { text: 'Your Heading Here', tag: 'h2', alignment: 'left', fontSize: '3xl', fontWeight: 'bold' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-icon',
    name: 'icon',
    category: 'content',
    description: 'Standalone icon element with size and color controls',
    icon: 'star',
    schema: {
      type: 'object',
      properties: {
        icon: { type: 'string', title: 'Icon (emoji)' },
        size: { type: 'string', title: 'Size', enum: ['small', 'medium', 'large', 'xl', '2xl'] },
        color: { type: 'string', title: 'Color' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        linkUrl: { type: 'string', title: 'Link URL' },
        linkTarget: { type: 'string', title: 'Link Target', enum: ['_self', '_blank'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        backgroundShape: { type: 'string', title: 'Background Shape', enum: ['none', 'circle', 'square', 'rounded'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { icon: '\u2B50', size: 'large', alignment: 'center' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-icon-box',
    name: 'icon-box',
    category: 'content',
    description: 'Icon with title and description card',
    icon: 'sparkles',
    schema: {
      type: 'object',
      properties: {
        icon: { type: 'string', title: 'Icon (emoji)' },
        title: { type: 'string', title: 'Title' },
        description: { type: 'string', title: 'Description' },
        iconSize: { type: 'string', title: 'Icon Size', enum: ['small', 'medium', 'large', 'xl'] },
        iconColor: { type: 'string', title: 'Icon Color' },
        iconPosition: { type: 'string', title: 'Icon Position', enum: ['top', 'left', 'right'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        titleTag: { type: 'string', title: 'Title Tag', enum: ['h3', 'h4', 'h5', 'h6'] },
        linkUrl: { type: 'string', title: 'Link URL' },
        linkTarget: { type: 'string', title: 'Link Target', enum: ['_self', '_blank'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        borderWidth: { type: 'string', title: 'Border Width', enum: ['none', '1', '2'] },
        borderColor: { type: 'string', title: 'Border Color' },
        shadow: { type: 'string', title: 'Shadow', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { icon: '\uD83D\uDE80', title: 'Feature Title', description: 'A short description of this feature or service.', iconPosition: 'top', alignment: 'center', padding: 'medium', borderRadius: 'medium' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-image-box',
    name: 'image-box',
    category: 'content',
    description: 'Image with title and description card',
    icon: 'image',
    schema: {
      type: 'object',
      properties: {
        imageUrl: { type: 'string', title: 'Image URL' },
        imageAlt: { type: 'string', title: 'Image Alt Text' },
        title: { type: 'string', title: 'Title' },
        description: { type: 'string', title: 'Description' },
        imagePosition: { type: 'string', title: 'Image Position', enum: ['top', 'left', 'right', 'bottom'] },
        imageHeight: { type: 'string', title: 'Image Height', enum: ['small', 'medium', 'large', 'auto'] },
        objectFit: { type: 'string', title: 'Object Fit', enum: ['cover', 'contain'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        titleTag: { type: 'string', title: 'Title Tag', enum: ['h3', 'h4', 'h5', 'h6'] },
        linkUrl: { type: 'string', title: 'Link URL' },
        linkTarget: { type: 'string', title: 'Link Target', enum: ['_self', '_blank'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        shadow: { type: 'string', title: 'Shadow', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: 'Image Box Title', description: 'A short description below the image.', imagePosition: 'top', imageHeight: 'medium', objectFit: 'cover', alignment: 'center', padding: 'medium', borderRadius: 'medium' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-icon-list',
    name: 'icon-list',
    category: 'content',
    description: 'List of items with custom icons',
    icon: 'list',
    schema: {
      type: 'object',
      properties: {
        items: { type: 'array', title: 'Items', items: { type: 'object', properties: { icon: { type: 'string' }, text: { type: 'string' }, linkUrl: { type: 'string' } } } },
        layout: { type: 'string', title: 'Layout', enum: ['vertical', 'horizontal'] },
        iconColor: { type: 'string', title: 'Icon Color' },
        iconSize: { type: 'string', title: 'Icon Size', enum: ['small', 'medium', 'large'] },
        textColor: { type: 'string', title: 'Text Color' },
        fontSize: { type: 'string', title: 'Font Size', enum: ['small', 'base', 'large'] },
        spacing: { type: 'string', title: 'Spacing', enum: ['tight', 'normal', 'relaxed'] },
        divider: { type: 'boolean', title: 'Show Dividers' },
        dividerColor: { type: 'string', title: 'Divider Color' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { items: [{ icon: '\u2705', text: 'First item' }, { icon: '\u2705', text: 'Second item' }, { icon: '\u2705', text: 'Third item' }], layout: 'vertical', alignment: 'left' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-tabs',
    name: 'tabs',
    category: 'content',
    description: 'Tabbed content panels',
    icon: 'layout-left',
    schema: {
      type: 'object',
      properties: {
        tabs: { type: 'array', title: 'Tabs', items: { type: 'object', properties: { title: { type: 'string' }, content: { type: 'string' }, icon: { type: 'string' } } } },
        defaultTab: { type: 'number', title: 'Default Tab Index' },
        tabPosition: { type: 'string', title: 'Tab Position', enum: ['top', 'left'] },
        tabAlignment: { type: 'string', title: 'Tab Alignment', enum: ['left', 'center', 'right', 'stretch'] },
        activeColor: { type: 'string', title: 'Active Color' },
        activeTextColor: { type: 'string', title: 'Active Text Color' },
        inactiveColor: { type: 'string', title: 'Inactive Color' },
        inactiveTextColor: { type: 'string', title: 'Inactive Text Color' },
        contentBackgroundColor: { type: 'string', title: 'Content Background' },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { tabs: [{ title: 'Tab 1', content: 'Content for tab 1' }, { title: 'Tab 2', content: 'Content for tab 2' }, { title: 'Tab 3', content: 'Content for tab 3' }], defaultTab: 0, tabPosition: 'top', tabAlignment: 'left', borderRadius: 'small', padding: 'medium' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-progress-bar',
    name: 'progress-bar',
    category: 'content',
    description: 'Horizontal progress bars with labels',
    icon: 'chart',
    schema: {
      type: 'object',
      properties: {
        items: { type: 'array', title: 'Progress Items', items: { type: 'object', properties: { label: { type: 'string' }, percentage: { type: 'number' }, color: { type: 'string' } } } },
        barColor: { type: 'string', title: 'Bar Color' },
        barBackgroundColor: { type: 'string', title: 'Bar Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        showPercentage: { type: 'boolean', title: 'Show Percentage' },
        barHeight: { type: 'string', title: 'Bar Height', enum: ['thin', 'medium', 'thick'] },
        barBorderRadius: { type: 'string', title: 'Bar Border Radius', enum: ['none', 'small', 'full'] },
        spacing: { type: 'string', title: 'Spacing', enum: ['small', 'medium', 'large'] },
        animated: { type: 'boolean', title: 'Animated' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        maxWidth: { type: 'string', title: 'Max Width', enum: ['full', 'container', 'narrow'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { items: [{ label: 'Web Design', percentage: 90 }, { label: 'Development', percentage: 85 }, { label: 'Marketing', percentage: 70 }], showPercentage: true, barHeight: 'medium', barBorderRadius: 'full', spacing: 'medium', animated: true, padding: 'medium', maxWidth: 'container' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-star-rating',
    name: 'star-rating',
    category: 'content',
    description: 'Star rating display',
    icon: 'star',
    schema: {
      type: 'object',
      properties: {
        rating: { type: 'number', title: 'Rating' },
        maxStars: { type: 'number', title: 'Max Stars' },
        size: { type: 'string', title: 'Size', enum: ['small', 'medium', 'large', 'xl'] },
        filledColor: { type: 'string', title: 'Filled Color' },
        emptyColor: { type: 'string', title: 'Empty Color' },
        showNumber: { type: 'boolean', title: 'Show Number' },
        numberPosition: { type: 'string', title: 'Number Position', enum: ['left', 'right'] },
        label: { type: 'string', title: 'Label' },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { rating: 4.5, maxStars: 5, size: 'medium', filledColor: '#FBBF24', emptyColor: '#374151', showNumber: true, numberPosition: 'right', alignment: 'center' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },
  {
    id: 'tpl-alert',
    name: 'alert',
    category: 'content',
    description: 'Alert/notice box for announcements',
    icon: 'info',
    schema: {
      type: 'object',
      properties: {
        message: { type: 'string', title: 'Message' },
        title: { type: 'string', title: 'Title' },
        type: { type: 'string', title: 'Type', enum: ['info', 'success', 'warning', 'error'] },
        icon: { type: 'string', title: 'Icon (emoji)' },
        showIcon: { type: 'boolean', title: 'Show Icon' },
        dismissible: { type: 'boolean', title: 'Dismissible' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        textColor: { type: 'string', title: 'Text Color' },
        borderColor: { type: 'string', title: 'Border Color' },
        borderWidth: { type: 'string', title: 'Border Width', enum: ['none', '1', '2', '4'] },
        borderRadius: { type: 'string', title: 'Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { message: 'This is an important notice.', type: 'info', showIcon: true, borderWidth: '1', borderRadius: 'medium', padding: 'medium', alignment: 'left' },
    thumbnail: null,
    order: 19,
    isActive: true,
  },

  // ─── New Marketing Components ───────────────────────────────
  {
    id: 'tpl-countdown',
    name: 'countdown',
    category: 'marketing',
    description: 'Countdown timer to a target date',
    icon: 'timer',
    schema: {
      type: 'object',
      properties: {
        targetDate: { type: 'string', title: 'Target Date (ISO)' },
        title: { type: 'string', title: 'Title' },
        expiredMessage: { type: 'string', title: 'Expired Message' },
        layout: { type: 'string', title: 'Layout', enum: ['inline', 'boxes'] },
        showDays: { type: 'boolean', title: 'Show Days' },
        showHours: { type: 'boolean', title: 'Show Hours' },
        showMinutes: { type: 'boolean', title: 'Show Minutes' },
        showSeconds: { type: 'boolean', title: 'Show Seconds' },
        numberColor: { type: 'string', title: 'Number Color' },
        labelColor: { type: 'string', title: 'Label Color' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        boxBackgroundColor: { type: 'string', title: 'Box Background Color' },
        boxBorderRadius: { type: 'string', title: 'Box Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        fontSize: { type: 'string', title: 'Font Size', enum: ['small', 'medium', 'large', 'xl'] },
        alignment: { type: 'string', title: 'Alignment', enum: ['left', 'center', 'right'] },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        customClassName: { type: 'string', title: 'Custom CSS Class' },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { targetDate: '', title: 'Offer Ends In', expiredMessage: 'This offer has expired', layout: 'boxes', showDays: true, showHours: true, showMinutes: true, showSeconds: true, fontSize: 'large', alignment: 'center', boxBorderRadius: 'medium', padding: 'medium' },
    thumbnail: null,
    order: 15,
    isActive: true,
  },

  // ─── E-commerce ────────────────────────────────────────────────
  {
    id: 'tpl-product-showcase',
    name: 'product-showcase',
    category: 'ecommerce',
    description: 'Product grid showcase',
    icon: 'store',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        productIds: { type: 'string', title: 'Product IDs (comma-separated)' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4'] },
        showPrices: { type: 'boolean', title: 'Show Prices' },
        showRatings: { type: 'boolean', title: 'Show Ratings' },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        cardBackgroundColor: { type: 'string', title: 'Card Background' },
        cardBorderRadius: { type: 'string', title: 'Card Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: '', productIds: '', columns: '4', showPrices: true, showRatings: true },
    thumbnail: null,
    order: 40,
    isActive: true,
  },
  {
    id: 'tpl-category-grid',
    name: 'category-grid',
    category: 'ecommerce',
    description: 'Category grid with icons',
    icon: 'category',
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', title: 'Title' },
        columns: { type: 'string', title: 'Columns', enum: ['2', '3', '4', '6'] },
        categories: { type: 'array', title: 'Categories', items: { type: 'object', properties: { name: { type: 'string' }, icon: { type: 'string' }, link: { type: 'string' }, count: { type: 'string' } } } },
        backgroundColor: { type: 'string', title: 'Background Color' },
        padding: { type: 'string', title: 'Padding', enum: ['none', 'small', 'medium', 'large'] },
        margin: { type: 'string', title: 'Margin', enum: ['none', 'small', 'medium', 'large'] },
        cardBackgroundColor: { type: 'string', title: 'Card Background' },
        cardBorderRadius: { type: 'string', title: 'Card Border Radius', enum: ['none', 'small', 'medium', 'large'] },
        hideOnMobile: { type: 'boolean', title: 'Hide on Mobile' },
      },
    },
    defaultProps: { title: '', columns: '4', categories: [] },
    thumbnail: null,
    order: 41,
    isActive: true,
  },
]
